//! Genie's own tables.
//!
//! # Why these are declared here and not in the server's generated schema
//!
//! Spec 032 FR-004 and ADR-063: a pack owns the tables it writes. These six
//! were in `src/server/src/schema.rs`, generated by `diesel print-schema` from
//! the live database, which meant the server declared tables only this pack
//! has ever read or written — and meant this pack could not touch them at all
//! without the server's help.
//!
//! `src/server/diesel.toml` now excludes them from generation
//! (`print_schema.filter.except_tables`), so there is exactly one declaration
//! of each and it is here. Regenerating the server's schema will not bring
//! them back; if it ever does, the filter has been lost and there are two
//! declarations of one table again, which is the drift this spec spent six
//! increments removing.
//!
//! The migrations that create them still live in `src/server/migrations`.
//! Splitting the migration directory is a separate decision — Diesel reads one
//! per invocation — and nothing about owning the *declaration* depends on it.

// Named only so `joinable!` below can point this pack's foreign keys at them.
use thunderforge_server::schema::{users, world_actors, world_items, worlds};

diesel::table! {
    world_genie_puzzle_clock_rewards (id) {
        id -> Uuid,
        clock_id -> Uuid,
        trigger_segment -> Int4,
        reward_resource_type -> Nullable<Text>,
        reward_resource_amount -> Nullable<Int4>,
        reward_item_id -> Nullable<Uuid>,
        reward_item_quantity -> Nullable<Int4>,
        recipient_mode -> Text,
        granted_at -> Nullable<Timestamp>,
        created_by -> Uuid,
        created_at -> Timestamp,
    }
}
diesel::table! {
    world_genie_puzzle_clocks (id) {
        id -> Uuid,
        session_id -> Uuid,
        label -> Text,
        segments_current -> Int4,
        segments_max -> Int4,
        resolved_at -> Nullable<Timestamp>,
        created_at -> Timestamp,
        updated_at -> Timestamp,
    }
}
diesel::table! {
    world_genie_resource_holdings (id) {
        id -> Uuid,
        session_id -> Uuid,
        actor_id -> Uuid,
        resource_type -> Text,
        quantity -> Int4,
        created_at -> Timestamp,
        updated_at -> Timestamp,
    }
}
diesel::table! {
    world_genie_sessions (id) {
        id -> Uuid,
        world_id -> Uuid,
        wishes_remaining -> Int4,
        doom_clock_current -> Int4,
        doom_clock_max -> Int4,
        status -> Text,
        created_by -> Uuid,
        created_at -> Timestamp,
        updated_at -> Timestamp,
    }
}
diesel::table! {
    world_genie_shop_listings (id) {
        id -> Uuid,
        actor_id -> Uuid,
        item_id -> Uuid,
        price_kind -> Text,
        price_resource_type -> Nullable<Text>,
        price_resource_amount -> Nullable<Int4>,
        price_item_id -> Nullable<Uuid>,
        price_item_quantity -> Nullable<Int4>,
        created_by -> Uuid,
        created_at -> Timestamp,
    }
}
diesel::table! {
    world_genie_trade_proposals (id) {
        id -> Uuid,
        session_id -> Uuid,
        from_actor_id -> Uuid,
        from_resource_type -> Text,
        from_quantity -> Int4,
        to_actor_id -> Uuid,
        to_resource_type -> Text,
        to_quantity -> Int4,
        status -> Text,
        created_by -> Uuid,
        created_at -> Timestamp,
        updated_at -> Timestamp,
    }
}

diesel::joinable!(world_genie_puzzle_clock_rewards -> users (created_by));
diesel::joinable!(world_genie_puzzle_clock_rewards -> world_genie_puzzle_clocks (clock_id));
diesel::joinable!(world_genie_puzzle_clock_rewards -> world_items (reward_item_id));
diesel::joinable!(world_genie_puzzle_clocks -> world_genie_sessions (session_id));
diesel::joinable!(world_genie_resource_holdings -> world_actors (actor_id));
diesel::joinable!(world_genie_resource_holdings -> world_genie_sessions (session_id));
diesel::joinable!(world_genie_sessions -> users (created_by));
diesel::joinable!(world_genie_sessions -> worlds (world_id));
diesel::joinable!(world_genie_shop_listings -> users (created_by));
diesel::joinable!(world_genie_shop_listings -> world_actors (actor_id));
diesel::joinable!(world_genie_trade_proposals -> users (created_by));
diesel::joinable!(world_genie_trade_proposals -> world_genie_sessions (session_id));

// Which tables may appear in one query together.
//
// Invoked per pair rather than as one list, and that is a constraint rather
// than a style: the macro generates an impl for every pair it is given, and a
// pair of two *server* tables would be an impl on two foreign types, which the
// orphan rule forbids. Every invocation below therefore names at least one
// table this crate owns.
diesel::allow_tables_to_appear_in_same_query!(
    world_genie_puzzle_clock_rewards,
    world_genie_puzzle_clocks,
    world_genie_resource_holdings,
    world_genie_sessions,
    world_genie_shop_listings,
    world_genie_trade_proposals,
);
