[workspace]
resolver = "3"
members = [
    "src/server", 
    "src/core", 
    "src/engine", 
    "crates/pack_system_spec",
    "crates/thunderforge-canvas-core",
    "packs/systems/dnd5e/server",
    "packs/systems/dnd5e/engine"
]
default-members = ["src/server", "src/core"]

[profile.release]
# less code to include into binary
panic = 'abort'
# optimization over all codebase ( better optimization, slower build )
codegen-units = 1
# optimization for size ( more aggressive )
opt-level = 3
# optimization for size
# opt-level = 's'
# link time optimization using using whole-program analysis
lto = true
