//! The generated fixtures (spec 048 T067).
//!
//! Each fixture is generated by `fixtures/gen.rs` from invented characters,
//! and its sha256 is pinned here, so a change to the generator or a
//! character is a visible diff. Regenerate the committed files with
//! `THUNDERFORGE_WRITE_FIXTURES=1 cargo test -p thunderforge-system-roll-for-shoes-sheet --test fixtures`,
//! then update the pins.

#[path = "fixtures/gen.rs"]
mod generator;

use std::path::PathBuf;

use sha2::{Digest, Sha256};
use thunderforge_pdf::Document;

const PINNED: &[(&str, &str)] = &[
    (
        "wren-4.pdf",
        "55eb7538a353495f21aa46acd70519f333f5f3977addd6c1639f6848763a7322",
    ),
    (
        "wren-5.pdf",
        "c570c2b3b96a6bca5424311000c7e6491fa6ba23dc8b7daf18271e825d97e928",
    ),
    (
        "misprinted-lineage.pdf",
        "67d01ae325f58f83193b945220b47df6cba6566d11b790afba14295c14f8672a",
    ),
    (
        "not-a-rfs-sheet.pdf",
        "534baf89a427c2880fd6e6f8614b5ea3048f0370f14dd8c8ac0fee336240c0f9",
    ),
];

fn generated() -> Vec<(&'static str, Vec<u8>)> {
    let mut out: Vec<(&'static str, Vec<u8>)> = generator::all()
        .iter()
        .map(|c| (c.file, generator::sheet(c)))
        .collect();
    out.push(("not-a-rfs-sheet.pdf", generator::not_a_sheet()));
    out
}

fn dir() -> PathBuf {
    PathBuf::from(env!("CARGO_MANIFEST_DIR")).join("tests/fixtures")
}

fn sha256(bytes: &[u8]) -> String {
    Sha256::digest(bytes)
        .iter()
        .map(|b| format!("{b:02x}"))
        .collect()
}

#[test]
fn generation_is_deterministic() {
    assert!(generated() == generated(), "two runs wrote different bytes");
}

#[test]
fn the_committed_fixtures_are_the_generated_ones() {
    let fixtures = generated();
    if std::env::var_os("THUNDERFORGE_WRITE_FIXTURES").is_some() {
        for (file, bytes) in &fixtures {
            std::fs::write(dir().join(file), bytes).expect("write fixture");
        }
    }
    let table: Vec<String> = fixtures
        .iter()
        .map(|(file, bytes)| format!("    (\"{file}\", \"{}\"),", sha256(bytes)))
        .collect();
    for (file, bytes) in &fixtures {
        let pinned = PINNED.iter().find(|(name, _)| name == file);
        assert_eq!(
            pinned.map(|(_, hash)| *hash),
            Some(sha256(bytes).as_str()),
            "{file}: the pin does not match; the generated table is\n{}",
            table.join("\n")
        );
        let committed = std::fs::read(dir().join(file)).expect("committed fixture");
        assert!(
            &committed == bytes,
            "{file}: the committed file is not the generated one"
        );
    }
    assert_eq!(PINNED.len(), fixtures.len(), "a pin names no fixture");
}

/// The values sit in widget fields on the one page.
#[test]
fn the_fixtures_read_back() {
    for character in generator::all() {
        let bytes = generator::sheet(&character);
        let doc = Document::from_bytes(&bytes).expect("parses");
        let pages = doc.pages();
        assert_eq!(pages.len(), 1, "{}", character.file);
        let mut read = std::collections::BTreeMap::new();
        for field in doc.form_fields(&pages[0]) {
            if !field.value.is_empty() {
                read.insert(field.name, field.value);
            }
        }
        assert_eq!(
            read,
            generator::field_values(&character),
            "{}",
            character.file
        );
    }
}
