import { test, expect, type Browser, type Page } from "@playwright/test";
import {
  freshCredentials,
  graphql,
  openDockTab,
  register,
  registerAndCreateWorld,
  uniqueSuffix,
} from "./fixtures/helpers";
import { createNpcViaCompendium } from "./fixtures/content";

/**
 * The demo: everything from an empty browser to two people at the same table.
 *
 * # Why this file exists when eighty others already pass
 *
 * Every leg of this journey is already tested. Registration, world creation,
 * system choice, the compendium, scenes, invites, claiming, the play dock —
 * each has a spec that checks it thoroughly, in isolation, from a fixture that
 * skips whatever the spec is not about.
 *
 * Nothing walks the whole path. And the whole path is the product: nobody
 * registers in order to register, they register because they want to run a
 * game on Thursday. A suite of green legs can hide a broken journey, because a
 * fixture that sets state up directly never notices that the *screen* that
 * normally sets it up has no button any more.
 *
 * So this file uses the interface for everything a person would use the
 * interface for. Invites are generated by clicking Generate Join Link, not by
 * calling `generateInviteCode`. The player joins by visiting the link and
 * pressing Join Campaign. The character is claimed from the list the player is
 * actually shown. Where a fixture is used at all — `createNpcViaCompendium` —
 * it is because that fixture *is* the clicked flow, factored out.
 *
 * # What it deliberately leaves alone
 *
 * Pixel-level canvas authoring: drawing walls, placing torches, dragging
 * shapes. `canvas-authoring.spec.ts` and `map-editor-tooling.spec.ts` own that
 * and own it better, with helpers that know why a synthetic click needs a
 * frame boundary in the middle of it. Duplicating them here would add fragility
 * and no coverage. What this asserts about the canvas is what a person would
 * assert from the doorway: it came up, and it is showing the right scene.
 *
 * # Reading a failure here
 *
 * Every step is a named `test.step`, so a failure names the moment the journey
 * broke rather than a line number. If this file fails and the focused specs all
 * pass, the bug is in a join — something two features have to agree about and
 * only one of them was ever asked.
 */

const GM_PASSWORD_SAFE_TIMEOUT = 180_000;

/** The world's system, chosen the way a GM chooses it: from the picker. */
async function chooseSystem(
  page: Page,
  worldId: string,
  title: string,
): Promise<void> {
  await page.goto(`/world/${worldId}/settings/system`);
  const picker = page.getByTestId("system-picker");
  await expect(picker).toBeVisible({ timeout: 15_000 });
  await picker.click();
  await page.getByRole("option", { name: title }).click();

  const warning = page.getByTestId("system-change-warning");
  if (await warning.isVisible().catch(() => false)) {
    await page.getByTestId("system-change-accept-risk").click();
  }
  await page
    .getByTestId("pending-system-confirmation")
    .getByRole("button", { name: /confirm/i })
    .click();
  await expect(page.getByTestId("active-system-card")).toContainText(title, {
    timeout: 15_000,
  });
}

/** A scene, made through the dock exactly as the Settings tab offers it. */
async function createScene(page: Page, name: string): Promise<void> {
  await openDockTab(page, "settings");
  const newSceneButton = page.getByTestId("new-scene-button");
  await expect(newSceneButton).toBeVisible({ timeout: 15_000 });
  await newSceneButton.click();
  await page.locator('[data-testid="new-scene-name-input"]:visible').fill(name);
  await page.locator('[data-testid="create-scene-submit"]:visible').click();
  await expect(page.getByTestId("new-scene-name-input")).toBeHidden({
    timeout: 10_000,
  });
}

/**
 * Launches a scene from the Scenes page, which is the one surface that sets
 * the world's *active* scene rather than this client's selection (ADR-046).
 * Returns its id, which is only stated plainly in the detail route's path.
 */
async function launchScene(
  page: Page,
  worldId: string,
  sceneName: string,
): Promise<string> {
  await page.goto(`/world/${worldId}/scenes`);
  await page.getByRole("link", { name: sceneName }).click();
  await page.waitForURL(new RegExp(`/world/${worldId}/scenes/[^/]+$`), {
    timeout: 15_000,
  });
  const sceneId = /\/scenes\/([^/?#]+)/.exec(new URL(page.url()).pathname)?.[1];
  if (!sceneId) {
    throw new Error(`could not read a scene id from ${page.url()}`);
  }
  await page.getByTestId("launch-scene-button").click();
  await page.waitForURL(new RegExp(`/world/${worldId}/play`), {
    timeout: 20_000,
  });
  return sceneId;
}

/** Which scene this client's session is on, asked as whoever holds the page. */
async function activeSceneId(
  page: Page,
  worldId: string,
): Promise<string | null> {
  const result = await graphql<{
    data?: { world?: { activeSceneId?: string | null } };
  }>(page, `query ($id: UUID!) { world(id: $id) { activeSceneId } }`, {
    id: worldId,
  });
  return result.data?.world?.activeSceneId ?? null;
}

/** The canvas is up. Not "the map is correct" — that is other specs' work. */
async function expectCanvasLive(page: Page): Promise<void> {
  await expect(page.locator("canvas")).toBeVisible({ timeout: 20_000 });
}

/** Marks an actor claimable, from the actor's own page, as a GM would. */
async function markClaimable(
  gmPage: Page,
  worldId: string,
  actorId: string,
): Promise<void> {
  await gmPage.goto(`/world/${worldId}/actor/${actorId}/view`);
  const checkbox = gmPage
    .getByTestId("actor-claim-block")
    .locator('input[type="checkbox"]');
  await checkbox.click();
  await expect(checkbox).toBeChecked({ timeout: 10_000 });
}

/** A player character: made as an NPC, then flipped, which is the only path. */
async function createPlayerCharacter(
  gmPage: Page,
  worldId: string,
  label: string,
): Promise<string> {
  const actorId = await createNpcViaCompendium(gmPage, worldId, label);
  await gmPage.goto(`/world/${worldId}/actor/${actorId}/edit`);
  await gmPage.getByLabel(/this is a player character/i).check();
  await gmPage.getByRole("button", { name: "Save" }).click();
  await expect(gmPage.getByText(/^saved\.?$/i)).toBeVisible({
    timeout: 10_000,
  });
  return actorId;
}

/** The join link, read off the screen the GM actually presses. */
async function generateJoinLink(
  gmPage: Page,
  worldId: string,
): Promise<string> {
  await gmPage
    .context()
    .grantPermissions(["clipboard-read", "clipboard-write"]);
  await gmPage.goto(`/world/${worldId}`);
  await gmPage.getByRole("button", { name: "Generate Join Link" }).click();

  // The link is put in a read-only field for the GM to copy, so this reads it
  // the same way rather than reaching into the clipboard — the field being
  // populated is part of what the step is checking.
  const field = gmPage.locator("input[readonly]").first();
  await expect(field).toBeVisible({ timeout: 15_000 });
  const url = await field.inputValue();
  const code = new URL(url).pathname.split("/").pop() ?? "";
  if (!code) {
    throw new Error(`No invite code in the link shown on screen ("${url}")`);
  }
  return code;
}

test.describe("The demo: from an empty browser to a table with two people at it", () => {
  test("a Game Master signs up, builds a world, and gets a scene on screen", async ({
    page,
  }) => {
    test.setTimeout(GM_PASSWORD_SAFE_TIMEOUT);
    const suffix = uniqueSuffix();
    let worldId = "";

    await test.step("signs up and lands somewhere that tells them what to do", async () => {
      worldId = await registerAndCreateWorld(page, `Demo World ${suffix}`);
      // Registration ends on world creation and world creation ends on
      // staging: at no point is a new user left on a page with nothing on it.
      expect(new URL(page.url()).pathname).toMatch(/\/world\/[^/]+\/staging$/);
    });

    await test.step("picks the ruleset the table plays", async () => {
      await chooseSystem(page, worldId, "Genie");
    });

    await test.step("writes their first character into the compendium", async () => {
      const actorId = await createNpcViaCompendium(
        page,
        worldId,
        `Innkeeper ${suffix}`,
      );
      await page.goto(`/world/${worldId}/actor/${actorId}/view`);
      // The system's own sheet is what draws, because the world has a system.
      // This is the join the pack-discovery work is about: a container that
      // lives in the pack, mounted by a page that never names it.
      await expect(page.getByTestId("genie-actor-sheet")).toBeVisible({
        timeout: 15_000,
      });
    });

    await test.step("builds a scene and puts it on the table", async () => {
      await page.goto(`/world/${worldId}/play`);
      await expectCanvasLive(page);
      await createScene(page, `Tavern ${suffix}`);
      await launchScene(page, worldId, `Tavern ${suffix}`);
      await expectCanvasLive(page);
    });

    await test.step("has the tools a running game needs, without hunting", async () => {
      for (const tab of ["chat", "actors", "combat", "settings"]) {
        await expect(
          page.getByTestId(`world-dock-tab-${tab}`),
          `a GM mid-session should be able to reach ${tab}`,
        ).toBeVisible({ timeout: 10_000 });
      }
    });
  });

  test("a player joins by link, claims a character, and follows the GM into the scene", async ({
    browser,
  }: {
    browser: Browser;
  }) => {
    test.setTimeout(GM_PASSWORD_SAFE_TIMEOUT);
    const suffix = uniqueSuffix();

    const gmContext = await browser.newContext({
      permissions: ["clipboard-read", "clipboard-write"],
    });
    const gmPage = await gmContext.newPage();
    const playerContext = await browser.newContext();
    const playerPage = await playerContext.newPage();

    try {
      let worldId = "";
      let joinCode = "";
      const heroName = `Vashti ${suffix}`;

      await test.step("the GM prepares a world, a scene, and a character to hand out", async () => {
        worldId = await registerAndCreateWorld(gmPage, `Demo Table ${suffix}`);
        await chooseSystem(gmPage, worldId, "Genie");

        const heroId = await createPlayerCharacter(gmPage, worldId, heroName);
        await markClaimable(gmPage, worldId, heroId);

        await gmPage.goto(`/world/${worldId}/play`);
        await expectCanvasLive(gmPage);
        // Two scenes, because one proves nothing. Creating a scene already
        // makes it the world's active one, so a test that launches the only
        // scene there is cannot tell "the GM's launch moved the table" from
        // "it was already there" — the first draft of this file could not,
        // and said so confidently. The table starts in the Bazaar and the GM
        // moves it to the Souk while the player is watching.
        await createScene(gmPage, `Bazaar ${suffix}`);
        await createScene(gmPage, `Souk ${suffix}`);
        await launchScene(gmPage, worldId, `Bazaar ${suffix}`);
      });

      await test.step("the GM presses Generate Join Link and gets something to send", async () => {
        joinCode = await generateJoinLink(gmPage, worldId);
        expect(joinCode.length, "a join link with no code in it").toBeGreaterThan(
          0,
        );
      });

      await test.step("the player signs up and uses the link", async () => {
        await register(playerPage, freshCredentials("demoplayer"));
        await playerPage.goto(`/join/${joinCode}`);
        await playerPage.getByRole("button", { name: "Join Campaign" }).click();
        // Joining a world that has characters on offer asks who you are before
        // it shows you anything else.
        await playerPage.waitForURL(
          new RegExp(`/world/${worldId}/actor-select$`),
          { timeout: 20_000 },
        );
      });

      await test.step("the player is offered the character the GM set aside, and takes it", async () => {
        const rows = playerPage.getByTestId("available-actor-row");
        await expect(rows).toHaveCount(1);
        await expect(rows.first()).toContainText(heroName);
        await rows.first().getByRole("button", { name: "Select" }).click();
        await playerPage.waitForURL(new RegExp(`/world/${worldId}$`), {
          timeout: 20_000,
        });
      });

      await test.step("the GM launches the scene and the player is already looking at it", async () => {
        await playerPage.goto(`/world/${worldId}/play`);
        await expectCanvasLive(playerPage);

        const before = await activeSceneId(playerPage, worldId);
        const sceneId = await launchScene(gmPage, worldId, `Souk ${suffix}`);
        expect(
          before,
          "the table should start somewhere other than where it is moving to",
        ).not.toBe(sceneId);

        // What a player can legitimately observe here is narrower than it
        // looks, and the first draft of this step got it wrong. The scene
        // switcher is empty for them — correctly: a scene is hidden when
        // created (spec 022 FR-003) and `scenes(worldId:)` filters hidden
        // scenes out for non-GMs, so a player has no scene *list* at all.
        //
        // What they do get is the scene being played. So the question worth
        // asking is whether this player's session followed, and their own
        // client is the honest place to ask it.
        await expect
          .poll(async () => activeSceneId(playerPage, worldId), {
            message:
              "the player's session should move to the scene the GM launched",
            timeout: 30_000,
          })
          .toBe(sceneId);

        // And the map is actually on screen for them. This is the specific
        // failure `WorldPage` documents at length: a player once sat under a
        // permanent "Loading scene…" over a canvas that had in fact fully
        // loaded, because the scene record they needed was filtered away from
        // them. No reload here — if that came back, this is where it shows.
        await expectCanvasLive(playerPage);
        await expect(
          playerPage.getByText("Loading scene…"),
          "the player should not be left under a loading overlay",
        ).toBeHidden({ timeout: 30_000 });
      });

      await test.step("the player can open their own character while the map stays up", async () => {
        await openDockTab(playerPage, "actors");
        const sheetButton = playerPage
          .getByTestId(/^actor-view-/)
          .first();
        await expect(sheetButton).toBeVisible({ timeout: 20_000 });
        await sheetButton.click();

        await expect(
          playerPage.getByTestId("in-pane-character-sheet"),
        ).toBeVisible({ timeout: 20_000 });
        // Principle I: opening a sheet is a dock change, not a scene change.
        // The engine keeps running behind it.
        await expectCanvasLive(playerPage);
      });
    } finally {
      await gmContext.close();
      await playerContext.close();
    }
  });
});
