import { expect, test, type Page } from "./fixtures/test";
import {
  graphql,
  inviteAndJoinAsPlayer,
  registerAndCreateWorld,
  setWorldSystem,
  uniqueSuffix,
} from "./fixtures/helpers";
import {
  bringIn,
  claimNamedCharacter,
  openBroughtByPlayers,
  openImport,
  review,
  stagedIn,
  stagedPiece,
  withSheetImportOn,
} from "./fixtures/sheetImport";
import { must } from "../playtest/table";

/**
 * Spec 048 User Story 3: what a player brings in on a sheet waits for the
 * Game Master, or a Trusted Player, to adopt it into the world.
 *
 * The sheets are `fighter-5.pdf` (Brannoc Vell) and `fighter3-wizard2.pdf`
 * (Isolde Maraven), generated by the 5e pack's tests from invented
 * characters. Both carry the feat Alert. The worlds are new and hold no
 * compendium, so everything either sheet names is staged at first.
 */

test.describe.configure({ mode: "serial" });
withSheetImportOn();

async function abilityNames(page: Page, actorId: string): Promise<string[]> {
  const { actorAbilities } = await must<{
    actorAbilities: { abilityName: string }[];
  }>(
    page,
    `query ($actorId: UUID!) { actorAbilities(actorId: $actorId) { abilityName } }`,
    { actorId },
  );
  return actorAbilities.map((entry) => entry.abilityName);
}

async function meOf(page: Page): Promise<{ id: string }> {
  const { me } = await must<{ me: { id: string } }>(
    page,
    `query { me { id } }`,
    {},
  );
  return me;
}

async function aDnd5eWorld(gm: Page, name: string): Promise<string> {
  const worldId = await registerAndCreateWorld(
    gm,
    `E2E ${name} ${uniqueSuffix()}`,
  );
  await setWorldSystem(gm, worldId, "dnd5e");
  return worldId;
}

test.describe("Spec 048: adopting what players brought in", () => {
  test("the GM adopts a feat in one action, a second character that brought it uses the world's, and a Player can neither see the queue nor adopt", async ({
    page: gm,
    browser,
  }) => {
    test.setTimeout(360_000);
    const worldId = await aDnd5eWorld(gm, "Sheet Adopt");
    const first = await claimNamedCharacter(browser, gm, worldId);
    const second = await claimNamedCharacter(browser, gm, worldId);
    try {
      await bringIn(first.player, worldId, first.actorId, "fighter-5.pdf");
      const alert = await stagedPiece(gm, worldId, "feat", "Alert");
      expect(alert.state).toBe("PENDING");
      expect(await abilityNames(gm, first.actorId)).not.toContain("Alert");

      // One action on the queue, and the feat is the world's.
      await openBroughtByPlayers(gm, worldId);
      const row = gm.getByTestId("staged-row").filter({ hasText: "Alert" });
      await expect(row).toHaveAttribute("data-state", "PENDING");
      await row.getByRole("button", { name: "Adopt Alert" }).click();
      await expect(row).toHaveAttribute("data-state", "ACCEPTED", {
        timeout: 15_000,
      });
      await expect(row.getByRole("button")).toHaveCount(0);

      // SC-005: it is in the world's compendium, and on the character.
      await gm.goto(`/world/${worldId}/compendium?tab=abilities`);
      // The catalog opens on spells; a feat is under its own tab.
      await gm.getByRole("tab", { name: /^Feats/ }).click();
      await expect(gm.getByTestId("ability-catalog-table")).toContainText(
        "Alert",
        { timeout: 20_000 },
      );
      await expect
        .poll(() => abilityNames(first.player, first.actorId), {
          timeout: 15_000,
        })
        .toContain("Alert");

      // A second character that brings the same feat uses the world's: it
      // is matched in the review, and nothing new is staged for it.
      await openImport(second.player, worldId, second.actorId);
      await review(second.player, "fighter3-wizard2.pdf");
      await expect(
        second.player.getByTestId("sheet-import-content-feat-Alert"),
      ).toHaveAttribute("data-resolution", "world");
      await second.player.getByTestId("sheet-import-accept").click();
      await expect(second.player).toHaveURL(
        new RegExp(`/world/${worldId}/actor/${second.actorId}/view$`),
        { timeout: 30_000 },
      );
      expect(await abilityNames(second.player, second.actorId)).toContain(
        "Alert",
      );
      const alerts = (await stagedIn(gm, worldId)).filter(
        (piece) => piece.name === "Alert",
      );
      expect(alerts.map((piece) => piece.id)).toEqual([alert.id]);

      // A Player has no queue: the tab is not offered, and asking for it
      // lands on the compendium's first tab.
      await first.player.goto(`/world/${worldId}/compendium?tab=brought`);
      await expect(
        first.player.getByRole("tablist", { name: "Sections" }),
      ).toBeVisible({
        timeout: 20_000,
      });
      await expect(
        first.player.getByRole("tab", { name: "Brought by players" }),
      ).toHaveCount(0);
      await expect(
        first.player.getByRole("region", { name: "Brought by players" }),
      ).toHaveCount(0);

      // And the server refuses them. Each sheet describes its Longsword
      // differently, so each player staged their own: take the first's.
      const firstId = (await meOf(first.player)).id;
      const sword = await stagedPiece(
        gm,
        worldId,
        "item",
        "Longsword",
        firstId,
      );
      const refused = await graphql<{
        errors?: { extensions?: { code?: string } }[];
      }>(
        first.player,
        `
          mutation ($id: UUID!) {
            adoptStagedContent(id: $id) {
              id
            }
          }
        `,
        { id: sword.id },
      );
      expect(refused.errors?.[0]?.extensions?.code).toBe("FORBIDDEN");
      expect(
        (await stagedPiece(gm, worldId, "item", "Longsword", firstId)).state,
      ).toBe("PENDING");
    } finally {
      await first.player.context().close();
      await second.player.context().close();
    }
  });

  test("a Trusted Player adopts all of one player's content at once", async ({
    page: gm,
    browser,
  }) => {
    test.setTimeout(300_000);
    const worldId = await aDnd5eWorld(gm, "Sheet Adopt All");
    const { player, actorId } = await claimNamedCharacter(browser, gm, worldId);
    const trusted = await inviteAndJoinAsPlayer(
      browser,
      gm,
      worldId,
      "e2etrusted",
    );
    try {
      await must(
        gm,
        `mutation ($input: UpdateMemberRoleInput!) {
          updateMemberRole(input: $input) { id }
        }`,
        {
          input: {
            worldId,
            userId: (await meOf(trusted)).id,
            role: "TrustedPlayer",
          },
        },
      );
      await bringIn(player, worldId, actorId, "fighter-5.pdf");
      const brought = await stagedIn(gm, worldId);
      const pending = brought.filter((piece) => piece.state === "PENDING");
      expect(pending.length).toBeGreaterThan(1);
      const playerId = pending[0].broughtBy.id;
      expect(pending.every((piece) => piece.broughtBy.id === playerId)).toBe(
        true,
      );

      await openBroughtByPlayers(trusted, worldId);
      const group = trusted
        .getByTestId("staged-player")
        .and(trusted.locator(`[data-player-id="${playerId}"]`));
      await expect(group.getByTestId("staged-row")).toHaveCount(brought.length);
      await group.getByRole("button", { name: /^Adopt all from / }).click();
      await expect(
        group.locator('[data-testid="staged-row"][data-state="PENDING"]'),
      ).toHaveCount(0, { timeout: 20_000 });
      await expect(
        group.locator('[data-testid="staged-row"][data-state="ACCEPTED"]'),
      ).toHaveCount(pending.length);

      // On the server too, and the character holds the world's pieces.
      const after = await stagedIn(gm, worldId);
      expect(after.filter((piece) => piece.state === "PENDING")).toEqual([]);
      const names = await abilityNames(player, actorId);
      expect(names).toContain("Alert");
    } finally {
      await player.context().close();
      await trusted.context().close();
    }
  });
});
