import { expect, test, type Page } from "./fixtures/test";
import {
  graphql,
  inviteAndJoinAsPlayer,
  registerAndCreateWorld,
  setWorldSystem,
  uniqueSuffix,
} from "./fixtures/helpers";
import {
  claimNamedCharacter,
  createNpc,
  importsOf as importRecords,
  review as reviewSheet,
  withSheetImportOn,
} from "./fixtures/sheetImport";
import { must } from "../playtest/table";

/**
 * Spec 048 User Story 1: a player brings a D&D Beyond character onto the
 * actor they hold, from the Players screen, and nothing is written until
 * they accept the review.
 *
 * The sheet is `fighter3-wizard2.pdf`, generated by the 5e pack's tests from
 * an invented character (Isolde Maraven, Fighter 3 / Wizard 2): no real
 * export is used. The world is new and holds no compendium, so every spell
 * and feature the sheet names is staged for the GM.
 *
 * The flag is off by default; this file switches it on for its run and puts
 * back what it found, as `instance-feature-flags.spec.ts` does.
 */

test.describe.configure({ mode: "serial" });
withSheetImportOn();

async function importsOf(page: Page, actorId: string): Promise<number> {
  return (await importRecords(page, actorId)).length;
}

async function abilityNames(page: Page, actorId: string): Promise<string[]> {
  const { actorAbilities } = await must<{
    actorAbilities: { abilityName: string }[];
  }>(
    page,
    `query ($actorId: UUID!) { actorAbilities(actorId: $actorId) { abilityName } }`,
    { actorId },
  );
  return actorAbilities.map((entry) => entry.abilityName);
}

async function proficiencies(page: Page, actorId: string): Promise<string> {
  const { actorSystemData } = await must<{
    actorSystemData: { proficiencyData: unknown } | null;
  }>(
    page,
    `query ($actorId: UUID!) {
      actorSystemData(actorId: $actorId) { proficiencyData }
    }`,
    { actorId },
  );
  return JSON.stringify(actorSystemData?.proficiencyData ?? null);
}

/** Pick the invented fighter-wizard and wait for the review. */
async function review(page: Page): Promise<void> {
  await reviewSheet(page, "fighter3-wizard2.pdf");
}

test.describe("Spec 048: a player brings a character in from a sheet", () => {
  test("the claim's holder reviews and accepts a D&D Beyond sheet, a declined review writes nothing, the GM imports onto an NPC, and another player is offered nothing", async ({
    page: gm,
    browser,
  }) => {
    test.setTimeout(300_000);
    const worldId = await registerAndCreateWorld(
      gm,
      `E2E Sheet Import ${uniqueSuffix()}`,
    );
    await setWorldSystem(gm, worldId, "dnd5e");
    const { player, actorId } = await claimNamedCharacter(browser, gm, worldId);
    const other = await inviteAndJoinAsPlayer(browser, gm, worldId, "e2enone");
    try {
      // The way in, from the Players screen.
      await player.goto(`/world/${worldId}/players`);
      const entry = player.getByTestId(`player-hero-import-${actorId}`);
      await expect(entry).toBeVisible({ timeout: 15_000 });
      await entry.click();
      await expect(player).toHaveURL(
        new RegExp(`/world/${worldId}/actor/${actorId}/import$`),
      );

      // The review: what the sheet writes, and what awaits the GM.
      await review(player);
      await expect(
        player.getByTestId("sheet-import-field-identity.name"),
      ).toContainText("Isolde Maraven");
      await expect(
        player.getByTestId("sheet-import-field-abilities.str"),
      ).toContainText("13");
      // The sheet lists Shield twice: the spell and the gear.
      const shield = player.getByTestId("sheet-import-content-spell-Shield");
      await expect(shield).toHaveAttribute("data-resolution", /staged/);
      expect(await importsOf(player, actorId)).toBe(0);

      await player.getByTestId("sheet-import-accept").click();
      await expect(player).toHaveURL(
        new RegExp(`/world/${worldId}/actor/${actorId}/view$`),
        { timeout: 30_000 },
      );

      // The sheet: both classes, level 5, the scores, hit points, coins.
      const sheet = player.getByTestId("dnd5e-actor-sheet");
      await expect(sheet).toBeVisible({ timeout: 15_000 });
      await expect(player.getByTestId("dnd5e-class-0")).toContainText(
        "Fighter 3",
      );
      await expect(player.getByTestId("dnd5e-class-1")).toContainText(
        "Wizard 2",
      );
      await expect(player.getByTestId("dnd5e-proficiency-bonus")).toContainText(
        "+3",
      );
      await expect(player.getByTestId("dnd5e-score-strength")).toContainText(
        "13",
      );
      await expect(
        player.getByTestId("dnd5e-score-intelligence"),
      ).toContainText("16");
      await expect(player.getByTestId("dnd5e-hit-points")).toContainText("38");
      await expect(player.getByTestId("dnd5e-coins-gp")).toHaveText("1215");
      expect(await proficiencies(player, actorId)).toContain("arcana");

      // Spells the world lacks are on the sheet, awaiting the GM, and absent
      // from what play reads.
      const linked = player.getByTestId("dnd5e-linked-content");
      const staged = linked
        .locator('li[data-kind="spell"]')
        .filter({ hasText: "Shield" });
      await expect(staged).toHaveAttribute("data-staged", "pending", {
        timeout: 15_000,
      });
      await expect(staged).toContainText("awaiting the GM");
      expect(await abilityNames(player, actorId)).not.toContain("Shield");
      expect(await importsOf(gm, actorId)).toBe(1);

      // A second run that declines writes nothing.
      await player.goto(`/world/${worldId}/actor/${actorId}/import`);
      await review(player);
      await player.getByTestId("sheet-import-decline").click();
      await expect(player).toHaveURL(
        new RegExp(`/world/${worldId}/actor/${actorId}/view$`),
      );
      expect(await importsOf(player, actorId)).toBe(1);

      // The GM brings the same sheet onto an NPC.
      const npcId = await createNpc(gm, worldId, "dnd5e");
      await gm.goto(`/world/${worldId}/actor/${npcId}/view`);
      await gm.getByTestId("actor-bring-in-sheet").click();
      await review(gm);
      await gm.getByTestId("sheet-import-accept").click();
      await expect(gm).toHaveURL(
        new RegExp(`/world/${worldId}/actor/${npcId}/view$`),
        { timeout: 30_000 },
      );
      await expect(gm.getByTestId("dnd5e-class-1")).toContainText("Wizard 2", {
        timeout: 15_000,
      });
      expect(await importsOf(gm, npcId)).toBe(1);

      // Another player is offered nothing, and the server refuses them.
      await other.goto(`/world/${worldId}/players`);
      await expect(other.getByTestId("players-list")).toBeVisible({
        timeout: 15_000,
      });
      await expect(
        other.getByTestId(`player-hero-import-${actorId}`),
      ).toHaveCount(0);
      await other.goto(`/world/${worldId}/actor/${actorId}/view`);
      await expect(other.getByTestId("dnd5e-actor-sheet")).toBeVisible({
        timeout: 15_000,
      });
      await expect(other.getByTestId("actor-bring-in-sheet")).toHaveCount(0);
      const refused = await graphql<{
        errors?: { extensions?: { code?: string } }[];
      }>(
        other,
        `
          query ($actorId: UUID!, $reading: JSON!) {
            sheetImportPreview(actorId: $actorId, reading: $reading) {
              planHash
            }
          }
        `,
        { actorId, reading: {} },
      );
      expect(refused.errors?.[0]?.extensions?.code).toBe("FORBIDDEN");
      expect(await importsOf(gm, actorId)).toBe(1);
    } finally {
      await player.context().close();
      await other.context().close();
    }
  });
});
