import { expect, test } from "./fixtures/test";
import {
  registerAndCreateWorld,
  setWorldSystem,
  uniqueSuffix,
} from "./fixtures/helpers";
import {
  claimNamedCharacter,
  createNpc,
  importsOf,
  review,
  withSheetImportOn,
} from "./fixtures/sheetImport";
import { must } from "../playtest/table";

/**
 * Spec 048 User Story 4 (T069): the import is the platform's, not the 5e
 * pack's. Roll for Shoes brings a character in from the one-page
 * ThunderForge sheet with nothing but its own reader, declaration and hook.
 *
 * The sheets are generated by the Roll for Shoes pack's tests from invented
 * characters: Wren Ashdown, and Odo Fenwick, whose sheet was filled in by
 * hand and gets its lineage wrong.
 */

test.describe.configure({ mode: "serial" });
withSheetImportOn();

const SYSTEM = "roll_for_shoes";

interface Skill {
  id: string;
  name: string;
  level: number;
  parentId: string | null;
}

async function systemData(
  page: import("@playwright/test").Page,
  actorId: string,
): Promise<{ skills: Skill[]; xp: unknown }> {
  const { actorSystemData } = await must<{
    actorSystemData: {
      traitData: { skills?: Skill[] } | null;
      resourceData: { xp?: unknown } | null;
    } | null;
  }>(
    page,
    `query ($actorId: UUID!) {
      actorSystemData(actorId: $actorId) { traitData resourceData }
    }`,
    { actorId },
  );
  return {
    skills: actorSystemData?.traitData?.skills ?? [],
    xp: actorSystemData?.resourceData?.xp,
  };
}

test.describe("Spec 048: a second system brings a character in", () => {
  test("a Roll for Shoes sheet lands its name, XP and skill lineage, and a misprinted lineage is flagged and still valid", async ({
    page: gm,
    browser,
  }) => {
    test.setTimeout(240_000);
    const worldId = await registerAndCreateWorld(
      gm,
      `E2E RFS Sheet Import ${uniqueSuffix()}`,
    );
    await setWorldSystem(gm, worldId, SYSTEM);

    // A player brings a clean sheet onto the character they hold.
    const { player, actorId: wren } = await claimNamedCharacter(
      browser,
      gm,
      worldId,
    );
    try {
      await player.goto(`/world/${worldId}/actor/${wren}/view`);
      await player.getByTestId("actor-bring-in-sheet").click();
      await review(player, "wren-4.pdf", SYSTEM);
      await expect(
        player.getByTestId("sheet-import-field-identity.name"),
      ).toContainText("Wren Ashdown");
      await expect(
        player.getByTestId("sheet-import-field-identity.xp"),
      ).toContainText("2");
      const skills = player.getByTestId("sheet-import-field-skills");
      await expect(skills).toHaveAttribute("data-certainty", "read");
      await expect(skills).toContainText("Hide in Shadows 3");
      expect(await importsOf(player, wren)).toHaveLength(0);

      await player.getByTestId("sheet-import-accept").click();
      await expect(player).toHaveURL(
        new RegExp(`/world/${worldId}/actor/${wren}/view$`),
        { timeout: 30_000 },
      );
      await expect(player.getByTestId("rfs-sheet")).toBeVisible({
        timeout: 15_000,
      });
      await expect(player.getByTestId("rfs-sheet")).toContainText("Pick Locks");
      const landed = await systemData(player, wren);
      expect(landed.xp).toBe(2);
      const byName = new Map(landed.skills.map((s) => [s.name, s]));
      expect(landed.skills.map((s) => s.name)).toEqual([
        "Do Anything",
        "Sneak",
        "Hide in Shadows",
        "Climb",
        "Pick Locks",
      ]);
      expect(byName.get("Hide in Shadows")?.parentId).toBe(
        byName.get("Sneak")?.id,
      );
      expect(byName.get("Climb")?.parentId).toBe(byName.get("Do Anything")?.id);
      expect(await importsOf(gm, wren)).toHaveLength(1);
    } finally {
      await player.context().close();
    }

    // A hand-filled sheet: the lineage is flagged, offers no retyping, and
    // what lands is still a lineage the pack takes.
    const odo = await createNpc(gm, worldId, SYSTEM);
    await gm.goto(`/world/${worldId}/actor/${odo}/import`);
    await review(gm, "misprinted-lineage.pdf", SYSTEM);
    const doubted = gm.getByTestId("sheet-import-field-skills");
    await expect(doubted).toHaveAttribute("data-certainty", "uncertain");
    await expect(doubted).toContainText("not a number");
    await expect(gm.getByTestId("sheet-import-correct-skills")).toHaveCount(0);
    await gm.getByTestId("sheet-import-accept").click();
    await expect(gm).toHaveURL(
      new RegExp(`/world/${worldId}/actor/${odo}/view$`),
      { timeout: 30_000 },
    );
    const misprinted = await systemData(gm, odo);
    expect(
      misprinted.skills.map((s) => [s.name, s.level, s.parentId === null]),
    ).toEqual([
      ["Do Anything", 1, true],
      ["Bake", 1, true],
      ["Bake Under Pressure", 4, true],
    ]);
  });
});
