import { expect, test, type Page } from "./fixtures/test";
import { openDockTab } from "./fixtures/helpers";
import {
  bringIn,
  stagedIn,
  withSheetImportOn,
  type StagedSeen,
} from "./fixtures/sheetImport";
import {
  addCombatant,
  claimFor,
  grantAbility,
  openCombatPanel,
  startCombat,
} from "../playtest/combat";
import {
  closeTable,
  must,
  openTable,
  placeCast,
  sitDown,
  type Table,
} from "../playtest/table";

/**
 * Spec 048 FR-037, FR-038, FR-038b: content the world has not adopted never
 * reaches the play field, a forced use is refused and reported to the Game
 * Master, and a client that was only stale is refused without a report.
 *
 * The sheet is `fighter3-wizard2.pdf` (invented, generated by the 5e pack's
 * tests). It carries the cantrip Fire Bolt as a spell and as an attack.
 */

test.describe.configure({ mode: "serial" });
withSheetImportOn();

interface Refused {
  codes: string[];
}

/**
 * `makeAttack` as `page`'s user, with `x-tf-last-event` set as a client
 * would set it, or left off. The fixtures' `graphql` sends no such header.
 */
async function attackWith(
  page: Page,
  input: Record<string, unknown>,
  lastEvent: string | null,
): Promise<Refused> {
  const csrf = (await page.context().cookies()).find(
    (cookie) => cookie.name === "csrf_token",
  )?.value;
  const response = await page.request.post("/api/graphql", {
    headers: {
      "Content-Type": "application/json",
      ...(csrf ? { "x-csrf-token": csrf } : {}),
      ...(lastEvent === null ? {} : { "x-tf-last-event": lastEvent }),
    },
    data: {
      query: `mutation ($input: AttackInput!) { makeAttack(input: $input) { id } }`,
      variables: { input },
    },
  });
  const body = (await response.json()) as {
    errors?: { extensions?: { code?: string } }[];
  };
  return {
    codes: (body.errors ?? []).map((error) => error.extensions?.code ?? ""),
  };
}

async function reportsOn(page: Page, worldId: string): Promise<string[]> {
  const { worldChatMessages } = await must<{
    worldChatMessages: { body: string; gmOnly: boolean }[];
  }>(
    page,
    `query ($worldId: UUID!) {
      worldChatMessages(worldId: $worldId, limit: 200) { body gmOnly }
    }`,
    { worldId },
  );
  return worldChatMessages
    .filter((message) => message.body.includes("has not been adopted"))
    .map((message) => message.body);
}

async function decline(gm: Page, piece: StagedSeen): Promise<void> {
  await must(
    gm,
    `mutation ($id: UUID!) { declineStagedContent(id: $id) { id } }`,
    { id: piece.id },
  );
}

/** The roll buttons the player's own sheet, in the dock, offers by name. */
async function rollsOnSheet(page: Page, actorId: string): Promise<string[]> {
  await openDockTab(page, "actors");
  const sheet = page.getByTestId("in-pane-character-sheet");
  if (!(await sheet.isVisible().catch(() => false))) {
    await page.getByTestId(`actor-view-${actorId}`).click();
  }
  await expect(sheet).toBeVisible({ timeout: 20_000 });
  return page.locator('[data-testid^="in-pane-roll-"]').allTextContents();
}

test.describe("Spec 048: what is not adopted stays off the table", () => {
  let table: Table;
  let actorId: string;
  let tokenId: string;
  let goblinTokenId: string;
  let fireBolts: StagedSeen[];
  let shield: StagedSeen;

  test.beforeAll(async ({ browser }, testInfo) => {
    test.setTimeout(300_000);
    const gm = await browser.newPage();
    table = await openTable({
      browser,
      gm,
      testInfo,
      system: "dnd5e",
      players: ["Isolde"],
    });
    const [seat] = table.players;
    ({ actorId, tokenId } = await placeCast(table, {
      label: "Isolde Maraven",
      at: { x: 300, y: 300 },
      seat,
    }));
    ({ tokenId: goblinTokenId } = await placeCast(table, {
      label: "Goblin",
      at: { x: 400, y: 300 },
      sheet: {
        scores: {
          strength: 8,
          dexterity: 14,
          constitution: 10,
          intelligence: 10,
          wisdom: 8,
          charisma: 8,
          armor_class: 13,
        },
        hitPoints: { current: 7, max: 7 },
      },
    }));
    await claimFor(table, seat, actorId);
    await bringIn(seat.page, table.worldId, actorId, "fighter3-wizard2.pdf");
    fireBolts = (await stagedIn(gm, table.worldId)).filter(
      (piece) => piece.name === "Fire Bolt",
    );
    expect(fireBolts.length).toBeGreaterThan(0);
    const spells = (await stagedIn(gm, table.worldId)).filter(
      (piece) => piece.kind === "spell" && piece.name === "Shield",
    );
    expect(spells).toHaveLength(1);
    [shield] = spells;
  });

  test.afterAll(async () => {
    if (!table) return;
    await closeTable(table);
    await table.gm.context().close();
  });

  test("a forced use of a piece nobody has decided is refused and reported to the Game Master only", async () => {
    const [seat] = table.players;
    const refused = await attackWith(
      seat.page,
      {
        attackerTokenId: tokenId,
        abilityId: shield.id,
        targetTokenId: goblinTokenId,
      },
      null,
    );
    expect(refused.codes).toEqual(["CONTENT_NOT_ADOPTED"]);

    await expect
      .poll(() => reportsOn(table.gm, table.worldId), { timeout: 15_000 })
      .toHaveLength(1);
    const [report] = await reportsOn(table.gm, table.worldId);
    expect(report).toContain("Shield");
    expect(report).toContain("Isolde Maraven");
    // The report is the Game Master's: the player's chat does not carry it.
    expect(await reportsOn(seat.page, table.worldId)).toEqual([]);
  });

  test("a declined spell is absent from the sheet and the combat panel, beside one the world granted", async () => {
    const [seat] = table.players;
    for (const piece of fireBolts) await decline(table.gm, piece);
    await grantAbility(table, actorId, {
      name: "Ember Lash",
      classification: "spell",
      grade: 0,
      effects: [
        { effectType: "ATTACK_ROLL", formula: "1d20+6" },
        { effectType: "DAMAGE", formula: "1d10" },
      ],
    });

    await sitDown(table, seat.page);
    // The rolls arrive after the sheet draws: wait for the granted one.
    await expect
      .poll(
        async () =>
          (await rollsOnSheet(seat.page, actorId)).some((text) =>
            text.includes("Ember Lash"),
          ),
        { timeout: 20_000 },
      )
      .toBe(true);
    const rolls = await rollsOnSheet(seat.page, actorId);
    expect(rolls.some((text) => text.includes("Fire Bolt"))).toBe(false);

    const combat = await startCombat(table);
    await addCombatant(table, combat.id, {
      label: "Isolde Maraven",
      actorId,
      tokenId,
      initiative: 15,
    });
    await openCombatPanel(seat.page);
    await expect(seat.page.getByTestId("combatant-row")).toContainText(
      "Isolde Maraven",
      { timeout: 15_000 },
    );
    await expect(seat.page.getByTestId("combat-panel")).not.toContainText(
      "Fire Bolt",
    );
  });

  test("a client held stale across the decline is refused and nobody is accused", async () => {
    const [seat] = table.players;
    const before = await reportsOn(table.gm, table.worldId);
    // Not the piece already reported, so the ten-minute window cannot be
    // what keeps the report away.
    const [piece] = fireBolts;
    for (const lastEvent of ["0", null]) {
      const refused = await attackWith(
        seat.page,
        {
          attackerTokenId: tokenId,
          abilityId: piece.id,
          targetTokenId: goblinTokenId,
        },
        lastEvent,
      );
      expect(refused.codes).toEqual(["CONTENT_NOT_ADOPTED"]);
    }
    // Give a report the time it would have taken to arrive, then hold.
    await table.gm.waitForTimeout(2_000);
    expect(await reportsOn(table.gm, table.worldId)).toEqual(before);

    // The control: a client that has seen the decline is reported.
    const current = await attackWith(
      seat.page,
      {
        attackerTokenId: tokenId,
        abilityId: piece.id,
        targetTokenId: goblinTokenId,
      },
      String(Number.MAX_SAFE_INTEGER),
    );
    expect(current.codes).toEqual(["CONTENT_NOT_ADOPTED"]);
    await expect
      .poll(() => reportsOn(table.gm, table.worldId), { timeout: 15_000 })
      .toHaveLength(before.length + 1);
  });
});
