import { expect, test, type Page } from "./fixtures/test";
import {
  registerAndCreateWorld,
  setWorldSystem,
  uniqueSuffix,
} from "./fixtures/helpers";
import {
  bringIn,
  createNpc,
  importsOf,
  openImport,
  review,
  withSheetImportOn,
} from "./fixtures/sheetImport";
import { must } from "../playtest/table";

/**
 * Spec 048 User Story 5: a character brought in at level 5 comes back a
 * session later at level 6. The review shows what the new sheet changes,
 * not the whole sheet again, and what the table tracks in play stays.
 *
 * `fighter3-wizard2.pdf` and `fighter3-wizard2-l6.pdf` are generated by the
 * 5e pack's tests from one invented character (Isolde Maraven); the second
 * adds a wizard level, six hit points of maximum, and Scorching Ray.
 */

test.describe.configure({ mode: "serial" });
withSheetImportOn();

type Resources = Record<string, unknown> & {
  current_hp?: number;
  max_hp?: number;
};

async function resources(page: Page, actorId: string): Promise<Resources> {
  const { actorSystemData } = await must<{
    actorSystemData: { resourceData: Resources | null } | null;
  }>(
    page,
    `query ($actorId: UUID!) {
      actorSystemData(actorId: $actorId) { resourceData }
    }`,
    { actorId },
  );
  return actorSystemData?.resourceData ?? {};
}

/** The table takes some hit points off, as play would. */
async function setCurrentHp(
  page: Page,
  actorId: string,
  hp: number,
): Promise<void> {
  const data = { ...(await resources(page, actorId)), current_hp: hp };
  await must(
    page,
    `mutation ($input: GraphQLUpdateActorSystemDataInput!) {
      updateActorSystemData(input: $input) { id }
    }`,
    {
      input: {
        actorId,
        gameSystemId: "dnd5e",
        dataType: "resource_data",
        data,
      },
    },
  );
}

test.describe("Spec 048: bringing a character back in", () => {
  test("a level 6 sheet over a level 5 one shows only what changes, and the table's current HP survives", async ({
    page: gm,
  }) => {
    test.setTimeout(240_000);
    const worldId = await registerAndCreateWorld(
      gm,
      `E2E Sheet Reimport ${uniqueSuffix()}`,
    );
    await setWorldSystem(gm, worldId, "dnd5e");
    const actorId = await createNpc(gm, worldId, "dnd5e");

    await test.step("level 5 comes in", async () => {
      await bringIn(gm, worldId, actorId, "fighter3-wizard2.pdf");
      expect((await resources(gm, actorId)).max_hp).toBe(38);
    });

    await test.step("the table plays: Isolde is down to 9", async () => {
      await setCurrentHp(gm, actorId, 9);
      expect((await resources(gm, actorId)).current_hp).toBe(9);
    });

    await test.step("level 6: the review shows the differences", async () => {
      await openImport(gm, worldId, actorId);
      await review(gm, "fighter3-wizard2-l6.pdf");
      await expect(
        gm.getByRole("heading", { name: "What changes" }),
      ).toBeVisible();

      await expect(
        gm.getByTestId("sheet-import-field-resources.hp_max").first(),
      ).toHaveAttribute("data-change", "overwrites");
      // The name is the same on both sheets: it is not listed at all.
      await expect(
        gm.getByTestId("sheet-import-field-identity.name"),
      ).toHaveCount(0);

      // Content already on the character is counted, not listed again.
      await expect(
        gm.getByTestId("sheet-import-content-spell-Scorching Ray"),
      ).toBeVisible();
      await expect(
        gm.getByTestId("sheet-import-content-spell-Shield"),
      ).toHaveCount(0);
      await expect(
        gm.getByTestId("sheet-import-content-unchanged"),
      ).toContainText("on the character already, unchanged");
    });

    await test.step("accepting keeps the table's HP", async () => {
      await gm.getByTestId("sheet-import-accept").click();
      await expect(gm).toHaveURL(
        new RegExp(`/world/${worldId}/actor/${actorId}/view$`),
        { timeout: 30_000 },
      );
      const after = await resources(gm, actorId);
      expect(after.max_hp).toBe(44);
      expect(after.current_hp).toBe(9);
      expect(await importsOf(gm, actorId)).toHaveLength(2);
    });
  });
});
