import { expect, test, type Page } from "./fixtures/test";
import {
  openAdminPage,
  readSetting,
  writeSetting,
  writeSettingOrThrow,
} from "./fixtures/admin";
import {
  graphql,
  registerAndCreateWorld,
  setWorldSystem,
  uniqueSuffix,
} from "./fixtures/helpers";
import {
  SHEET_IMPORT_FLAG,
  bringIn,
  claimNamedCharacter,
  stagedIn,
} from "./fixtures/sheetImport";
import { must } from "../playtest/table";

/**
 * Spec 048 T089: `feature.sheet_import`, following
 * `instance-feature-flags.spec.ts`. Off, nobody is offered the button and
 * the server refuses an import whoever asks; what came in while it was on
 * stays usable: the GM still decides on staged content, and the player
 * still downloads their sheet. On again, the button is back.
 *
 * The flag is instance-wide and the shard runs one worker, so nothing else
 * imports while it is off. What was found is put back afterwards.
 *
 * The sheet is `fighter-5.pdf`, generated by the 5e pack's tests from an
 * invented character (Brannoc Vell).
 */

test.describe.configure({ mode: "serial" });

const PREVIEW = `
  query ($actorId: UUID!, $reading: JSON!) {
    sheetImportPreview(actorId: $actorId, reading: $reading) {
      planHash
    }
  }
`;

let admin: Page;
let original: string | null = null;

test.beforeAll(async ({ browser }) => {
  admin = await openAdminPage(browser);
  const found = await readSetting(admin, SHEET_IMPORT_FLAG);
  test.skip(
    found.source === "ENVIRONMENT",
    `${SHEET_IMPORT_FLAG} is fixed by ${found.fixedBy}`,
  );
  original = found.source === "INSTANCE" ? found.value : null;
  await writeSettingOrThrow(admin, SHEET_IMPORT_FLAG, "true");
});

test.afterAll(async () => {
  if (!admin) return;
  await writeSetting(admin, SHEET_IMPORT_FLAG, original);
  await admin.context().close();
});

test.describe("Spec 048: the sheet import flag", () => {
  test("off: no button and the server refuses, while staged decisions and downloads still work; on: the button is back", async ({
    page: gm,
    browser,
  }) => {
    test.setTimeout(300_000);
    const worldId = await registerAndCreateWorld(
      gm,
      `E2E Sheet Flag ${uniqueSuffix()}`,
    );
    await setWorldSystem(gm, worldId, "dnd5e");
    const { player, actorId } = await claimNamedCharacter(browser, gm, worldId);
    const view = `/world/${worldId}/actor/${actorId}/view`;
    try {
      await test.step("on: the player brings the sheet in", async () => {
        await bringIn(player, worldId, actorId, "fighter-5.pdf");
      });
      const pending = (await stagedIn(gm, worldId)).filter(
        (piece) => piece.state === "PENDING",
      );
      expect(pending.length).toBeGreaterThan(0);
      const { actorImports } = await must<{
        actorImports: { versionId: string | null }[];
      }>(
        player,
        `query ($actorId: UUID!) { actorImports(actorId: $actorId) { versionId } }`,
        { actorId },
      );
      const versionId = actorImports[0]?.versionId;
      expect(versionId).toBeTruthy();

      await writeSettingOrThrow(admin, SHEET_IMPORT_FLAG, "false");

      await test.step("off: nobody is offered the button", async () => {
        for (const page of [player, gm]) {
          await page.goto(view);
          await expect(page.getByTestId("import-history")).toBeVisible({
            timeout: 15_000,
          });
          await expect(page.getByTestId("actor-bring-in-sheet")).toHaveCount(0);
        }
      });

      await test.step("off: the server refuses an import", async () => {
        const refused = await graphql<{
          errors?: { extensions?: { code?: string } }[];
        }>(gm, PREVIEW, { actorId, reading: {} });
        expect(refused.errors?.[0]?.extensions?.code).toBe("FEATURE_DISABLED");
      });

      await test.step("off: the GM still adopts what came in", async () => {
        const { adoptStagedContent } = await must<{
          adoptStagedContent: { state: string };
        }>(
          gm,
          `mutation ($id: UUID!) { adoptStagedContent(id: $id) { state } }`,
          { id: pending[0].id },
        );
        expect(adoptStagedContent.state).toBe("ADOPTED");
      });

      await test.step("off: the player still downloads their sheet", async () => {
        const file = await player.request.get(
          `/api/sheet-imports/${versionId}/file`,
        );
        expect(file.status()).toBe(200);
        expect((await file.body()).subarray(0, 5).toString()).toBe("%PDF-");
      });

      await writeSettingOrThrow(admin, SHEET_IMPORT_FLAG, "true");

      await test.step("on again: the button is back", async () => {
        await player.goto(view);
        await expect(player.getByTestId("actor-bring-in-sheet")).toBeVisible({
          timeout: 15_000,
        });
      });
    } finally {
      await player.context().close();
    }
  });
});
