import { expect, test, type Page } from "./fixtures/test";
import { graphql } from "./fixtures/helpers";
import {
  bringIn,
  stagedPiece,
  withSheetImportOn,
} from "./fixtures/sheetImport";
import {
  addCombatant,
  advanceTurn,
  claimFor,
  gridSizeOf,
  startCombat,
} from "../playtest/combat";
import { closeTable, must, openTable, placeCast } from "../playtest/table";

/**
 * Spec 048, the combat neighbour (T064): a weapon brought in on a sheet is
 * refused in a fight until the Game Master adopts it, and once adopted it
 * is attacked with through `makeAttack`, at the to-hit and damage the sheet
 * printed.
 *
 * The sheet is `fighter-5.pdf` (Brannoc Vell, invented, generated by the 5e
 * pack's tests), whose Longsword is +6 to hit for 1d8+3 slashing.
 */

withSheetImportOn();

interface AttackMade {
  abilityName: string | null;
  outcome: string;
}

async function attack(
  page: Page,
  input: { attackerTokenId: string; itemId: string; targetTokenId: string },
): Promise<{ made: AttackMade[] | null; codes: string[] }> {
  const result = await graphql<{
    data?: { makeAttack: AttackMade[] } | null;
    errors?: { extensions?: { code?: string } }[];
  }>(
    page,
    `
      mutation ($input: AttackInput!) {
        makeAttack(input: $input) {
          abilityName
          outcome
        }
      }
    `,
    { input },
  );
  return {
    made: result.data?.makeAttack ?? null,
    codes: (result.errors ?? []).map((error) => error.extensions?.code ?? ""),
  };
}

test("an imported weapon is refused in a fight until adopted, and then it swings", async ({
  page,
  browser,
}, testInfo) => {
  test.setTimeout(6 * 60_000);
  const table = await openTable({
    browser,
    gm: page,
    testInfo,
    system: "dnd5e",
    players: ["Brannoc"],
  });
  const [seat] = table.players;
  try {
    const grid = await gridSizeOf(table);
    const hero = await placeCast(table, {
      label: "Brannoc Vell",
      at: { x: 0, y: 0 },
      seat,
    });
    // One square away: in a longsword's reach.
    const goblin = await placeCast(table, {
      label: "Goblin",
      at: { x: grid, y: 0 },
      tokenType: "npc",
      sheet: {
        scores: {
          strength: 8,
          dexterity: 14,
          constitution: 10,
          intelligence: 10,
          wisdom: 8,
          charisma: 8,
          armor_class: 13,
        },
        hitPoints: { current: 7, max: 7 },
      },
    });
    await claimFor(table, seat, hero.actorId);
    await bringIn(seat.page, table.worldId, hero.actorId, "fighter-5.pdf");

    let combat = await startCombat(table);
    for (const [label, cast, initiative] of [
      ["Brannoc Vell", hero, 20],
      ["Goblin", goblin, 5],
    ] as const) {
      combat = await addCombatant(table, combat.id, {
        label,
        actorId: cast.actorId,
        tokenId: cast.tokenId,
        initiative,
        isNpc: label === "Goblin",
      });
    }
    combat = await advanceTurn(table, combat.id);

    // Staged, the sword is not the world's, and the fight refuses it.
    const sword = await stagedPiece(
      table.gm,
      table.worldId,
      "item",
      "Longsword",
    );
    const refused = await attack(seat.page, {
      attackerTokenId: hero.tokenId,
      itemId: sword.id,
      targetTokenId: goblin.tokenId,
    });
    expect(refused.codes).toEqual(["CONTENT_NOT_ADOPTED"]);

    // The Game Master adopts it, and the character carries the world's.
    const { adoptStagedContent } = await must<{
      adoptStagedContent: { adoptedItemId: string | null };
    }>(
      table.gm,
      `mutation ($id: UUID!) {
        adoptStagedContent(id: $id) { adoptedItemId }
      }`,
      { id: sword.id },
    );
    const itemId = adoptStagedContent.adoptedItemId;
    expect(itemId).not.toBeNull();
    const { actorInventory } = await must<{
      actorInventory: { itemId: string | null; itemName: string }[];
    }>(
      seat.page,
      `query ($actorId: UUID!) {
        actorInventory(actorId: $actorId) { itemId itemName }
      }`,
      { actorId: hero.actorId },
    );
    expect(
      actorInventory.filter((entry) => entry.itemName === "Longsword"),
    ).toEqual([{ itemId, itemName: "Longsword" }]);

    // On their turn, the sword swings, as the sheet printed it.
    const made = await attack(seat.page, {
      attackerTokenId: hero.tokenId,
      itemId: itemId!,
      targetTokenId: goblin.tokenId,
    });
    expect(made.codes).toEqual([]);
    expect(made.made).toHaveLength(1);
    expect(made.made![0].abilityName).toBe("Longsword");
    expect(["HIT", "MISS"]).toContain(made.made![0].outcome);
  } finally {
    await closeTable(table);
  }
});
