import { expect, test, type Page } from "./fixtures/test";
import {
  graphql,
  inviteAndJoinAsPlayer,
  registerAndCreateWorld,
  setWorldSystem,
  uniqueSuffix,
} from "./fixtures/helpers";
import {
  bringIn,
  claimNamedCharacter,
  withSheetImportOn,
} from "./fixtures/sheetImport";
import { must } from "../playtest/table";

/**
 * Spec 048 User Story 5: the GM rolls a character back to before a bad
 * import. The sheet goes back; what the table tracks in play stays. The
 * history says what happened, the player cannot roll back, and only the
 * player and the GM can download the sheet that was brought in.
 *
 * The sheets are generated by the 5e pack's tests from one invented
 * character (Isolde Maraven) at level 5 and level 6.
 */

test.describe.configure({ mode: "serial" });
withSheetImportOn();

type Resources = Record<string, unknown> & {
  current_hp?: number;
  max_hp?: number;
};

interface Record_ {
  id: string;
  kind: string;
  versionNo: number | null;
  versionId: string | null;
}

async function resources(page: Page, actorId: string): Promise<Resources> {
  const { actorSystemData } = await must<{
    actorSystemData: { resourceData: Resources | null } | null;
  }>(
    page,
    `query ($actorId: UUID!) {
      actorSystemData(actorId: $actorId) { resourceData }
    }`,
    { actorId },
  );
  return actorSystemData?.resourceData ?? {};
}

async function history(page: Page, actorId: string): Promise<Record_[]> {
  const { actorImports } = await must<{ actorImports: Record_[] }>(
    page,
    `query ($actorId: UUID!) {
      actorImports(actorId: $actorId) { id kind versionNo versionId }
    }`,
    { actorId },
  );
  return actorImports;
}

test.describe("Spec 048: rolling a character back", () => {
  test("the GM rolls back a bad import and play state survives; the player cannot roll back but can download their sheet, and another player cannot", async ({
    page: gm,
    browser,
  }) => {
    test.setTimeout(300_000);
    const worldId = await registerAndCreateWorld(
      gm,
      `E2E Sheet Rollback ${uniqueSuffix()}`,
    );
    await setWorldSystem(gm, worldId, "dnd5e");
    const { player, actorId } = await claimNamedCharacter(browser, gm, worldId);
    const view = `/world/${worldId}/actor/${actorId}/view`;

    await test.step("the player brings level 5, then level 6", async () => {
      await bringIn(player, worldId, actorId, "fighter3-wizard2.pdf");
      await bringIn(player, worldId, actorId, "fighter3-wizard2-l6.pdf");
      expect((await resources(player, actorId)).max_hp).toBe(44);
    });

    await test.step("the table plays: Isolde is down to 9", async () => {
      const data = { ...(await resources(player, actorId)), current_hp: 9 };
      await must(
        player,
        `mutation ($input: GraphQLUpdateActorSystemDataInput!) {
          updateActorSystemData(input: $input) { id }
        }`,
        {
          input: {
            actorId,
            gameSystemId: "dnd5e",
            dataType: "resource_data",
            data,
          },
        },
      );
    });

    const imports = await history(gm, actorId);
    expect(imports.map((r) => r.kind)).toEqual(["import", "import"]);
    const [bad, first] = imports;

    await test.step("the player sees the history but no rollback", async () => {
      await player.goto(view);
      const panel = player.getByTestId("import-history");
      await expect(panel).toBeVisible({ timeout: 15_000 });
      await expect(panel.getByTestId("import-history-row")).toHaveCount(2);
      await expect(panel.getByTestId("import-history-rollback")).toHaveCount(0);

      const refused = await graphql<{
        errors?: { extensions?: { code?: string } }[];
      }>(
        player,
        `
          mutation ($actorId: UUID!, $toImportId: UUID!) {
            rollBackActor(actorId: $actorId, toImportId: $toImportId) {
              id
            }
          }
        `,
        { actorId, toImportId: bad.id },
      );
      expect(refused.errors?.[0]?.extensions?.code).toBe("FORBIDDEN");
    });

    await test.step("the GM rolls back to before version 2", async () => {
      await gm.goto(view);
      const panel = gm.getByTestId("import-history");
      await expect(panel.getByTestId("import-history-row")).toHaveCount(2, {
        timeout: 15_000,
      });
      const newest = panel.getByTestId("import-history-row").first();
      await expect(newest).toContainText("Version 2");
      await newest.getByTestId("import-history-rollback").click();
      await newest.getByTestId("import-history-confirm-rollback").click();
      await expect(panel.getByTestId("import-history-row")).toHaveCount(3, {
        timeout: 15_000,
      });
      await expect(
        panel.getByTestId("import-history-row").first(),
      ).toHaveAttribute("data-kind", "rollback");
      await expect(
        panel.getByTestId("import-history-row").first(),
      ).toContainText("Rolled back to before version 2");
    });

    await test.step("the sheet went back, the table's HP stayed", async () => {
      const after = await resources(gm, actorId);
      expect(after.max_hp).toBe(38);
      expect(after.current_hp).toBe(9);
      expect((await history(gm, actorId)).map((r) => r.kind)).toEqual([
        "rollback",
        "import",
        "import",
      ]);
    });

    await test.step("the player downloads their sheet; another player cannot", async () => {
      expect(first.versionId).toBeTruthy();
      const url = `/api/sheet-imports/${first.versionId}/file`;
      const mine = await player.request.get(url);
      expect(mine.status()).toBe(200);
      expect(mine.headers()["content-type"]).toContain("application/pdf");
      expect((await mine.body()).subarray(0, 5).toString()).toBe("%PDF-");

      const other = await inviteAndJoinAsPlayer(
        browser,
        gm,
        worldId,
        "e2eother",
      );
      const theirs = await other.request.get(url);
      expect(theirs.status()).toBe(404);
      await other.context().close();
    });

    await player.context().close();
  });
});
