// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Who may set it off, and whether the Game Master gets a say first.
 */
export type Activation = "anyone" | "gmOnly" | "requiresApproval";
