// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RefusalReason } from "./RefusalReason";

/**
 * What happens when somebody activates an interactive.
 *
 * A tagged outcome rather than a boolean, because "it did not run" covers
 * four genuinely different situations and a player told only "no" cannot tell
 * a locked door from a broken product.
 */
export type ActivationOutcome = { "outcome": "performed" } | { "outcome": "requested" } | { "outcome": "refused", reason: RefusalReason, } | { "outcome": "unavailable" } | { "outcome": "noEffect" };
