// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One attribute a game system declares.
 */
export type AttributeDeclaration = {
  /**
   * The system's own identifier — `might`, `strength`, `prowess`.
   */
  id: string;
  /**
   * What a person is shown.
   */
  label: string;
  /**
   * Short form for tight layouts, where the system offers one. Optional
   * because not every system has one: Pathfinder 2e's manifest declares
   * labels without abbreviations, and inventing "STR" for it would be this
   * crate deciding how another ruleset abbreviates.
   */
  abbreviation: string | null;
  /**
   * Where to read the value inside the actor's stored attribute slot.
   *
   * Defaults to `id`, which is what every shipping manifest relies on. It
   * exists so a system whose stored field names differ from its display
   * identifiers does not have to rename its stored data to adopt this.
   */
  source: string;
  /**
   * Declaration order, so a sheet reads the way its book does.
   */
  order: number;
};
