// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DistanceSource } from "./DistanceSource";

/**
 * The bright and dim reach of a light a character carries.
 */
export type CarriedLightDeclaration = { bright: DistanceSource | null, dim: DistanceSource | null, };
