// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One option in a [`ConfigFieldKind::Choice`].
 */
export type ChoiceOption = { value: string, label: string, };
