// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ChoiceOption } from "./ChoiceOption";

/**
 * The type of one configuration field.
 *
 * # There is deliberately no free-text kind
 *
 * A link effect must reference in-world content by identifier, never by
 * address. Without a free-text field in the vocabulary, a Game Master
 * *cannot* point an interactive at an arbitrary destination — not because a
 * rule forbids it but because there is nothing to type it into.
 *
 * That is what retires the hostile-destination edge case without an
 * allowlist (a moderation surface nobody agreed to own) or a confirmation
 * prompt (which puts the judgement on the player, who has the least context
 * about where the link came from). Adding a text kind here would quietly
 * bring all of that back.
 */
export type ConfigFieldKind = { "kind": "boolean" } | { "kind": "choice", options: Array<ChoiceOption>, } | { "kind": "reference", of: string, } | { "kind": "referenceList", of: string, };
