// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ChoiceOption } from "./ChoiceOption";

/**
 * One field a Game Master fills in when authoring an effect.
 */
export type ConfigField = { key: string, label: string, 
/**
 * Whether authoring is rejected without it.
 */
required: boolean, } & ({ "kind": "boolean" } | { "kind": "choice", options: Array<ChoiceOption>, } | { "kind": "reference", of: string, } | { "kind": "referenceList", of: string, });
