// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Pattern } from "./Pattern";

/**
 * Everything a system declares about finding its content in a document.
 *
 * A system that declares nothing cannot have a book read into it, and is
 * told so before a file is opened. That is a refusal rather than a fallback:
 * guessing with another system's vocabulary is how you import a Pathfinder
 * book as badly-parsed D&D.
 */
export type ContentPatterns = { patterns: Array<Pattern>, };
