// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { NameState } from "./NameState";
import type { ReadValue } from "./ReadValue";

/**
 * One thing read out of a book: a spell, an item, a creature, a feat.
 */
export type ContentEntry = { 
/**
 * The system's own word for what this is. Carried, never switched on.
 */
kind: string, name: string, 
/**
 * How much to trust the name. A block whose name could not be found is
 * still worth keeping when its declared fields read cleanly.
 */
nameState: NameState, 
/**
 * One-based page, so a Game Master can look it up in the real book.
 */
page: number, 
/**
 * The declared fields. Anchored kinds only; every declared field appears,
 * including the ones that were not found.
 */
values: { [key in string]: ReadValue }, 
/**
 * The entry's text. Prose kinds only.
 */
text: string | null, 
/**
 * Built from lines the layout pass did not trust (049 FR-004).
 */
suspect: boolean, 
/**
 * Whatever the system's own pack added that a declaration could not
 * express — a 5e creature's per-attack reach, for instance.
 *
 * Opaque on purpose. Shared code carries this and never looks inside it,
 * which is what lets a pack own a reading only it understands without
 * shared code learning that system's vocabulary.
 */
extras?: unknown, };
