// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DeclaredValueKind } from "./DeclaredValueKind";
import type { Origin } from "./Origin";

/**
 * One value a system publishes about an actor.
 *
 * The unit everything downstream carries and nothing downstream interprets.
 * A sheet lays these out, the canvas draws bars from some of them, and
 * neither knows what any of them mean.
 */
export type DeclaredValue = { 
/**
 * The system's own identifier — `strength`, `strengthMod`, `wishPoints`.
 */
id: string, 
/**
 * What a person is shown.
 */
label: string, 
/**
 * Short form for tight layouts, where the system offers one.
 */
abbreviation: string | null, value: DeclaredValueKind, origin: Origin, };
