// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What a declared value can be.
 *
 * Deliberately small. Every variant here is something at least one shipping
 * manifest already needs: scores and modifiers are integers, a Fate ladder
 * rung is text, a proficiency is a boolean, a condition set is a list. There
 * is no variant for a nested object, because a value a surface cannot render
 * without knowing what it means is a value this contract should not carry.
 */
export type DeclaredValueKind = { "kind": "integer", "value": number } | { "kind": "number", "value": number } | { "kind": "text", "value": string } | { "kind": "boolean", "value": boolean } | { "kind": "list", "value": Array<string> } | { "kind": "fraction", "value": { current: number, max: number | null, } } | { "kind": "track", "value": { filled: number, of: number, } } | { "kind": "state", "value": { current: string | null, 
/**
 * In the system's own order, worst last.
 */
options: Array<string>, } };
