// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DeclaredValueKind } from "./DeclaredValueKind";
import type { Origin } from "./Origin";

/**
 * One value a system publishes about an actor.
 *
 * The unit everything downstream carries and nothing downstream interprets.
 * A sheet lays these out, the canvas draws bars from some of them, and
 * neither knows what any of them mean.
 */
export type DeclaredValue = { 
/**
 * The system's own identifier — `strength`, `strengthMod`, `wishPoints`.
 */
id: string, 
/**
 * What a person is shown.
 */
label: string, 
/**
 * Short form for tight layouts, where the system offers one.
 */
abbreviation: string | null, value: DeclaredValueKind, 
/**
 * The group this belongs to, when it is part of one (FR-033).
 *
 * A Fate consequence is a severity *and* the aspect written into it; a
 * Cypher stat is a current value, a pool and an edge. Publishing those as
 * unrelated identifiers loses the fact that they are one thing, which is
 * what a sheet shows and a player reads.
 *
 * # Why a field rather than nesting
 *
 * Because `DeclaredValue` is flat and everything downstream relies on it:
 * the resolver, the wire type, the layout renderer and every test all
 * walk a list of values with an id. Nesting would change all of them to
 * gain one relationship. A group id names the relationship and leaves the
 * list a list.
 */
group?: string | null, 
/**
 * The group's own name, when its system gave it one (T019g).
 *
 * Without this a group was named after whichever member happened to be
 * declared first, which is a guess that was right by luck: Cypher's
 * `might` group leads with `might`, so it read "Might". Reorder the
 * manifest and the same group reads "Might Edge". A Fate consequence
 * group wants to read "Mild Consequence" whatever its parts are called.
 *
 * Repeated on every member of the group, and that repetition cannot
 * drift: the manifest declares a group **once**, in its own `groups`
 * block, and the server stamps the answer onto each value. Nothing
 * hand-writes it twice.
 */
groupLabel?: string | null, 
/**
 * This is the member to show when there is room for one (T019g).
 *
 * A group is several values and a compact layout has space for one of
 * them. Which one is a fact about the ruleset — a Cypher stat shows its
 * current value, not its edge — and nothing in the format could say it,
 * so the renderer took the first and hoped.
 *
 * False for a value in no group, and false for every member when the
 * system named no headline; a renderer with no headline falls back to
 * the first member, which is where this started.
 */
headline?: boolean, origin: Origin, };
