// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { DeclaredValueKind } from "./DeclaredValueKind";
import type { Origin } from "./Origin";

/**
 * One value a system publishes about an actor.
 *
 * The unit everything downstream carries and nothing downstream interprets.
 * A sheet lays these out, the canvas draws bars from some of them, and
 * neither knows what any of them mean.
 */
export type DeclaredValue = { 
/**
 * The system's own identifier — `strength`, `strengthMod`, `wishPoints`.
 */
id: string, 
/**
 * What a person is shown.
 */
label: string, 
/**
 * Short form for tight layouts, where the system offers one.
 */
abbreviation: string | null, value: DeclaredValueKind, 
/**
 * The group this belongs to, when it is part of one (FR-033).
 *
 * A Fate consequence is a severity *and* the aspect written into it; a
 * Cypher stat is a current value, a pool and an edge. Publishing those as
 * unrelated identifiers loses the fact that they are one thing, which is
 * what a sheet shows and a player reads.
 *
 * # Why a field rather than nesting
 *
 * Because `DeclaredValue` is flat and everything downstream relies on it:
 * the resolver, the wire type, the layout renderer and every test all
 * walk a list of values with an id. Nesting would change all of them to
 * gain one relationship. A group id names the relationship and leaves the
 * list a list.
 */
group?: string | null, origin: Origin, };
