// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ResourceEntry } from "./ResourceEntry";

/**
 * A resource as one viewer receives it.
 *
 * Tagged on `disclosure`, so the shape carries exactly the one field its
 * state permits and no other. An over-disclosing payload is unrepresentable
 * rather than forbidden by a rule somebody has to remember — and on the
 * TypeScript side this generates a discriminated union that narrows.
 */
export type Disclosed = { "disclosure": "visible", entries: Array<ResourceEntry>, } | { "disclosure": "greyed" } | { "disclosure": "percentage", proportion: number, } | { "disclosure": "chunked", quarter: number, };
