// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What a viewer other than the Game Master is permitted to learn.
 */
export type DisclosureState = "visible" | "greyed" | "percentage" | "chunked";
