// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Where one distance is read from an actor, and in what units.
 *
 * `slot` and `source` together, exactly as a `sheet` entry names them: which
 * of the actor's stored blobs, and which key inside it. One way to say "read
 * this field", not two.
 */
export type DistanceSource = { 
/**
 * Which of the actor's stored blobs to read — `traitData`,
 * `abilityData`, and so on. Absent means `traitData`, where a creature's
 * senses live in every system that has bothered to record them.
 */
slot: string | null, 
/**
 * The key inside that blob.
 */
source: string, 
/**
 * The system's own unit name — `feet`, `metres`. Recorded so a manifest
 * says what it means; the scene's own `per_cell` does the conversion,
 * because a scene that measures in metres measures *everything* in
 * metres.
 */
unit: string | null, 
/**
 * What to assume when the actor's sheet says nothing.
 *
 * Almost always absent. A default darkvision would give every creature
 * that failed to mention it the ability to see in the dark, which is the
 * same mistake a default flying speed would be.
 */
default: number | null, };
