// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ConfigField } from "./ConfigField";
import type { SubjectKind } from "./SubjectKind";

/**
 * What a subsystem contributes to become triggerable.
 *
 * Data, not behaviour — its three consumers need it in three places. The
 * handler lives in the plugin that owns the subsystem and never here.
 */
export type EffectDeclaration = { 
/**
 * Stable, namespaced by contributor — `door.set_state`, `light.toggle`.
 *
 * The namespace is what makes collision detection a prefix concern
 * rather than a coordination problem between teams.
 */
id: string, 
/**
 * What a Game Master is shown when choosing.
 */
label: string, 
/**
 * One line, in a GM's language rather than an engineer's.
 */
description: string, 
/**
 * Which subjects it may attach to. A door effect belongs on a door.
 */
subjectKinds: Array<SubjectKind>, 
/**
 * What the authoring form renders and the server validates.
 */
config: Array<ConfigField>, };
