// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Where one entry's numbers come from in a system's stored actor data.
 *
 * The server reads a system's JSONB slot and pulls the named fields. It never
 * learns what "health" means — only that this resource's first entry takes
 * its current from `current_hp` and its maximum from `max_hp`.
 *
 * That indirection is the whole point of FR-001. Without it, every new game
 * system would need server changes to be displayed, and the engine would
 * accumulate one special case per ruleset.
 */
export type EntrySource = {
  /**
   * Field holding this entry's current value.
   */
  current: string;
  /**
   * Field holding its maximum. Absent for a counter, or for a layer whose
   * size is whatever was granted — temporary hit points have no maximum of
   * their own.
   */
  max: string | null;
  /**
   * A maximum fixed by the rules rather than stored per character.
   *
   * Blades in the Dark caps stress at nine and trauma at four; neither is
   * written into a character's data because neither varies. Without this,
   * such a pool could only be shown as a bare count — losing the thing a
   * player most needs to see, which is how close to the cap they are.
   *
   * `max` wins when both are given: a stored value is about *this*
   * character, and a literal is about everyone.
   */
  maxValue: number | null;
  /**
   * Name for this layer, shown when there is more than one.
   */
  label: string | null;
  /**
   * Skip this entry when the field is missing or zero.
   *
   * Temporary hit points are usually absent, and an ever-present empty
   * "Temporary" layer would be visual noise on every character in the game.
   */
  optional: boolean;
};
