// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FieldKind } from "./FieldKind";

/**
 * One labelled field to read out of an anchored entry.
 */
export type FieldSpec = { 
/**
 * What the read value is called on the entry.
 */
key: string, 
/**
 * The label to look for in the document.
 */
label: string, 
/**
 * `as` in the manifest, because that reads correctly to a system author
 * writing JSON and is a reserved word to Rust.
 */
as: FieldKind, };
