// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What a field's text is meant to be.
 *
 * Three, and no more. A value that will not parse as its declared kind is
 * recorded *uncertain* with the text exactly as read — never coerced, never
 * dropped. A richer type language here would be a language, and the thing it
 * would buy is the ability to be confidently wrong about more fields.
 */
export type FieldKind = "integer" | "number" | "text";
