// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * How many times it may fire before a Game Master resets it.
 */
export type FireMode = "always" | "once";
