// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The speeds a creature has, in the scene's spoken units.
 *
 * Stated the way a stat block states them — "30 feet", "60 feet flying" —
 * rather than in cells, because that is what a book says and what somebody
 * types in. Converting to cells is the grid's business, not the sheet's.
 */
export type MovementSpeeds = { [key in string]: number };
