// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One movement type a system declares.
 */
export type MovementDeclaration = { 
/**
 * The system's own identifier — `walk`, `fly`, `stride`.
 */
id: string, 
/**
 * What a person is shown. Systems disagree even where ids match:
 * Pathfinder 2e calls its ground speed simply "Speed".
 */
label: string, 
/**
 * Where to read the value in the actor's stored sheet.
 */
source: string, 
/**
 * Speed to assume when the sheet says nothing.
 *
 * Only for the movement type every creature has — a ground speed. A
 * default on flight would give wings to everything that failed to
 * mention it, so most declarations leave this unset and are simply
 * absent for a creature that cannot move that way.
 */
default: number | null, order: number, };
