// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { NamePosition } from "./NamePosition";
import type { NamePreference } from "./NamePreference";
import type { NameStyle } from "./NameStyle";
import type { ProseEnd } from "./ProseEnd";

/**
 * How an entry's name is found.
 *
 * Every field is optional and which ones apply depends on the shape, because
 * a manifest is JSON somebody writes by hand and serde cannot key one
 * field's validity on another's value. The combination is checked by
 * `pack_system_spec::validate_system_manifest`, which is where a system
 * author gets told they wrote something that cannot work.
 */
export type NameRule = { 
/**
 * Anchored: which side of the anchor the name sits on.
 */
position: NamePosition | null, 
/**
 * Anchored: how many lines away to look. The 5e creature rule is six —
 * a statblock's name, its size-and-type line and its armour class are
 * not always adjacent.
 */
withinLines: number | null, 
/**
 * Anchored: which candidate line to take when several are in range.
 */
prefer: NamePreference | null, 
/**
 * Prose: what a name looks like.
 */
style: NameStyle | null, 
/**
 * Prose: where the entry stops.
 */
endsAt: ProseEnd | null, };
