// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Whether a value was read from stored data or computed from it.
 *
 * # Why a surface needs to know
 *
 * So it can tell a player which numbers they may edit. A 5e Strength score
 * is typed in; its modifier is not. A text box over a computed number invites
 * the two to disagree, and the stored one is the one that goes stale.
 */
export type Origin = "stored" | "derived";
