// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FieldSpec } from "./FieldSpec";
import type { NameRule } from "./NameRule";
import type { Shape } from "./Shape";

/**
 * One kind of content, and how to find it.
 */
export type Pattern = { 
/**
 * What this finds — `spell`, `creature`, `feat`. Open on purpose: shared
 * code never switches on the value, it only carries it through, so a
 * system may name kinds this repository has never heard of.
 */
kind: string, shape: Shape, 
/**
 * The label that unambiguously begins an entry. Anchored kinds only.
 *
 * "Unambiguously" is the whole requirement. A label that also occurs
 * inside an entry's prose will start entries in the middle of other
 * entries — which is why the 5e spell pattern anchors on `Casting Time`
 * and not on `Range`.
 */
anchor: string | null, name: NameRule, 
/**
 * The labels to read once an anchor is found. Anchored kinds only.
 */
fields: Array<FieldSpec>, 
/**
 * What confirms that a prose entry is one of *these*. Prose kinds only,
 * and required for them.
 *
 * Measured on 2026-09-12, and the reason this field exists: a prose kind
 * declared as "a heading, then paragraphs" describes **every section of
 * every book**. Without a discriminator the reader returned 72,974 magic
 * items across 246 books, including `Table of Contents` and `About`, and
 * returned exactly the same number for feats because the two declarations
 * were identical.
 *
 * At least one of these phrases must appear near the name for the entry
 * to count. A magic item is confirmed by its type line — `Wondrous item`,
 * `Weapon (`, `Potion` — and a feat by `Prerequisite`.
 */
confirmedBy: Array<string>, 
/**
 * How many lines after the name to look for a confirmation. Three by
 * default: a type line, a rarity, and one line of slack.
 */
confirmWithin: number | null, };
