// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What was read for one field, and how much to trust it.
 *
 * An enum rather than a `{ state, value }` pair so that **unread carries no
 * value by construction**. Spec 049 FR-002 says absence must be recorded as
 * absence and no value invented to fill it; a struct with an optional value
 * beside a state can express "unread, and here is the value anyway", and
 * anything expressible eventually gets written.
 */
export type ReadValue = { "state": "clear", "value": string } | { "state": "uncertain", "value": string } | { "state": "unread" };
