// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Why an activation was refused.
 */
export type RefusalReason = "gmOnly" | "locked" | "alreadyFired";
