// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The bounded area of a region interactive.
 *
 * Carried on the interactive rather than in `shapes`: a shape is authored
 * annotation the table sees, and a region is invisible and exists only to be
 * crossed. Storing them together would make every shape query filter out
 * regions and `visible_to_players` do two unrelated jobs.
 */
export type RegionGeometry = { "shape": "rect", x: number, y: number, width: number, height: number, } | { "shape": "polygon", 
/**
 * `[x, y]` pairs, in order. Implicitly closed.
 */
points: Array<[number, number]>, };
