// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One layer of a resource: a pool with its own maximum.
 */
export type ResourceEntry = {
  current: number;
  /**
   * Absent for a counter, which has no maximum to be a proportion of.
   */
  max: number | null;
  /**
   * Optional name for this layer — "Shield", "Stage 2".
   */
  label: string | null;
};
