// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { EntrySource } from "./EntrySource";

/**
 * Where a whole resource's entries come from.
 */
export type ResourceSource = { 
/**
 * Which stored slot to read: `resourceData`, `traitData`, and so on.
 */
slot: string, 
/**
 * Ordered. Index 0 is the base pool; later entries stack above it.
 */
entries: Array<EntrySource>, };
