// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * An attribute resolved for one actor.
 */
export type ResolvedAttribute = { id: string, label: string, abbreviation: string | null, value: number, };
