// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ResourceKind } from "./ResourceKind";

/**
 * What a game system declares it tracks.
 *
 * The engine holds no built-in notion of "health": one system tracks hit
 * points, another health/stamina/mana, a third health/energy. Hard-coding the
 * first would make every system after it a special case.
 */
export type ResourceDefinition = { id: string, label: string, kind: ResourceKind, 
/**
 * Display order. The engine imposes none.
 */
order: number, 
/**
 * Whether more than one entry is permitted.
 */
allowStacking: boolean, };
