// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Whether an entry of this kind carries labelled fields, or only prose.
 */
export type Shape = "anchored" | "prose";
