// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * One line of a document, as a reader sees it.
 *
 * The same shape the 5e statblock reader has always taken, lifted into
 * shared code so there is one of it. Deliberately not
 * `thunderforge_pdf::layout::Line`: that carries the geometry the layout
 * pass needed and a reader does not, and taking it here would tie every
 * reader to the PDF crate's internals.
 */
export type SourceLine = { text: string, size: number, bold: boolean, 
/**
 * One-based, as a person would cite it.
 */
page: number, 
/**
 * The layout pass did not trust the text on this line — letter-spaced,
 * or from a font this build cannot decode (049 FR-004).
 */
suspect: boolean, 
/**
 * Set larger or bolder than the body around it.
 *
 * Decided by the layout pass and carried here, the same way `suspect` is.
 * The layer that measured the page is the one that knows what its body
 * size was; a reader re-deciding it from a handful of lines would reach a
 * different answer for the same book.
 */
heading: boolean, };
