// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What a cell costs to enter, and to whom.
 */
export type TerrainCost = { 
/**
 * Multiplier applied to a step entering this cell. 2.0 is the usual
 * "difficult terrain".
 */
multiplier: number, 
/**
 * Movement types this does **not** apply to.
 *
 * The reason terrain is not simply a number: a creature flying over a
 * bog is not slowed by it, and a rule engine that cannot express that
 * forces every table to adjudicate flight by hand. Named rather than
 * inferred, because which types ignore which hazards is a ruleset's
 * decision and not this crate's.
 */
ignoredBy: Array<string>, };
