// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CarriedLightDeclaration } from "./CarriedLightDeclaration";
import type { DistanceSource } from "./DistanceSource";

/**
 * A system's whole `vision` block. Every part optional; absent means
 * ordinary sight.
 */
export type VisionDeclaration = { 
/**
 * How many of the system's own units one grid square is worth — 5, for
 * D&D 5e's five-foot square.
 *
 * Declared here because it exists nowhere else yet. A scene's `grid_size`
 * is **pixels** per cell, and no manifest records feet per square: the
 * `movement` block declares "30" and leaves the unit implicit, which
 * works only because nothing ever converts it. A distance that must be
 * drawn cannot be left implicit, so this block says what its numbers
 * mean. When `movement` needs the same answer, this is the declaration
 * to lift out and share rather than duplicate.
 *
 * Absent falls back to five, which is right for the systems that
 * measure in feet and harmless for the ones that declare no distances.
 */
unitsPerCell: number | null, 
/**
 * The unit's own name, for anything that shows a number to a person.
 */
unitLabel: string | null, darkvision: DistanceSource | null, carriedLight: CarriedLightDeclaration | null, };
