//! The list. Nothing in this file is a mechanism.
//!
//! Order matters twice over: it is the order the admin surface renders, and it
//! is the order the first-run wizard walks, so the group a declaration sits in
//! and the place that group first appears decide which step an operator meets
//! it on. Spec 064 FR-020 rests on exactly that — the legal duties precede the
//! sign-in providers because they are declared before them, with no sort
//! anywhere.

use super::{
    Backing, Capability, Kind, Requirement, SettingDeclaration, SetupVisibility, Validator,
};

const EMAIL: &[Validator] = &[
    Validator::NonEmptyAfterTrim,
    Validator::EmailSyntax,
    Validator::NoReservedTld,
    Validator::NotAShippedPlaceholder,
];
const NAME: &[Validator] = &[
    Validator::NonEmptyAfterTrim,
    Validator::NotAShippedPlaceholder,
];
const TEXT: &[Validator] = &[Validator::NonEmptyAfterTrim];
const NONE: &[Validator] = &[];

const MAIL_SECURITY: &[&str] = &["none", "starttls", "implicit"];
const ACCESS_POLICIES: &[&str] = &["open", "invite_only", "closed"];

pub(super) static DECLARATIONS: [SettingDeclaration; 43] = [
    // -- What kind of instance this is --------------------------------------
    //
    // First, and deliberately. Spec 052 US1/US2: what an operator is asked for
    // depends on what they are standing up, so the instance has to say what it
    // is before the wizard can know what it owes. `publishes_beyond_world` is
    // a statement, not an inference from the access policy — an invite-only
    // instance can run a public shelf, and an open instance can keep every
    // world private. Conflating the two asks the wrong person for a postal
    // address.
    SettingDeclaration {
        key: "instance.access_policy",
        kind: Kind::Enum(ACCESS_POLICIES),
        backing: Backing::AccessPolicy,
        env_var: Some("THUNDERFORGE_INSTANCE_ACCESS_POLICY"),
        env_aliases: &[],
        requirement: Requirement::Optional,
        setup: SetupVisibility::Asked,
        secret: false,
        // `invite_only`, agreeing with the migration that seeds this row on a
        // fresh install (spec 052 FR-004: every statement of the starting mode
        // must agree, and this one used to say `closed` while the migration
        // said `invite_only`). Nobody is locked out by it: admission bypasses
        // the policy entirely while no administrator exists.
        default: Some("invite_only"),
        validators: &[Validator::OneOf(ACCESS_POLICIES)],
        capability: None,
        what_to_set: "Who may create an account on this instance: `open` to anyone, `invite_only` to whoever holds an invitation link, or `closed` to nobody new.",
        what_is_limited: "Nothing \u{2014} the instance always has a policy.",
        group: "Access",
        since: "0.40",
    },
    SettingDeclaration {
        key: "instance.publishes_beyond_world",
        kind: Kind::Bool,
        backing: Backing::Row,
        env_var: Some("THUNDERFORGE_INSTANCE_PUBLISHES_BEYOND_WORLD"),
        env_aliases: &[],
        requirement: Requirement::Optional,
        setup: SetupVisibility::Asked,
        secret: false,
        default: Some("false"),
        validators: &[Validator::BoolLike],
        capability: None,
        what_to_set: "Whether content on this instance is published beyond the world it was made in \u{2014} a shared shelf, a public collection, anything a stranger can reach.",
        what_is_limited: "Nothing is refused while this is off. It decides what this instance is obliged to publish about itself, not what it can do.",
        group: "Access",
        since: "0.64",
    },
    // -- Who operates this instance -----------------------------------------
    SettingDeclaration {
        key: "operator.name",
        kind: Kind::Text,
        backing: Backing::Row,
        env_var: Some("THUNDERFORGE_OPERATOR_NAME"),
        env_aliases: &[],
        requirement: Requirement::RequiredAtSetup,
        setup: SetupVisibility::Asked,
        secret: false,
        default: None,
        validators: NAME,
        capability: Some(Capability::IdentifyOperator),
        what_to_set: "The name of the person or organisation that runs this instance, as it should appear on the legal pages.",
        what_is_limited: "The terms of service and privacy policy name nobody in particular.",
        group: "Operator",
        since: "0.40",
    },
    SettingDeclaration {
        key: "operator.contact_email",
        kind: Kind::Email,
        backing: Backing::Row,
        env_var: Some("THUNDERFORGE_OPERATOR_CONTACT_EMAIL"),
        env_aliases: &[],
        requirement: Requirement::RequiredAtSetup,
        setup: SetupVisibility::Asked,
        secret: false,
        default: None,
        validators: EMAIL,
        capability: Some(Capability::IdentifyOperator),
        what_to_set: "An address that reaches whoever runs this instance.",
        what_is_limited: "Nobody outside the instance can reach its operator.",
        group: "Operator",
        since: "0.40",
    },
    SettingDeclaration {
        key: "operator.jurisdiction",
        kind: Kind::Prose,
        backing: Backing::Row,
        env_var: Some("THUNDERFORGE_OPERATOR_JURISDICTION"),
        env_aliases: &[],
        requirement: Requirement::RequiredFor(Capability::PublishTerms),
        setup: SetupVisibility::AskedWhenPublishing,
        secret: false,
        default: None,
        validators: TEXT,
        capability: Some(Capability::PublishTerms),
        what_to_set: "The jurisdiction whose law the terms of service are read under.",
        what_is_limited: "The terms of service leave the governing law blank.",
        group: "Operator",
        since: "0.40",
    },
    // -- Where a copyright notice is served ---------------------------------
    //
    // Deliberately NOT `support_email`. 17 U.S.C. § 512(c)(2) treats the agent
    // a claim is served on as a different thing, with a different address
    // requirement, from "somebody will help you with the app".
    SettingDeclaration {
        key: "notice.contact_name",
        kind: Kind::Text,
        backing: Backing::Row,
        env_var: Some("THUNDERFORGE_NOTICE_CONTACT_NAME"),
        env_aliases: &[],
        requirement: Requirement::RequiredFor(Capability::PublishBeyondWorld),
        setup: SetupVisibility::AskedWhenPublishing,
        secret: false,
        default: None,
        validators: NAME,
        capability: Some(Capability::PublishBeyondWorld),
        what_to_set: "The name of the person or role a copyright notice is served on.",
        what_is_limited: "Content cannot be published beyond a world. Playing privately is unaffected.",
        group: "Copyright notices",
        since: "0.40",
    },
    SettingDeclaration {
        key: "notice.contact_email",
        kind: Kind::Email,
        backing: Backing::Row,
        env_var: Some("THUNDERFORGE_NOTICE_CONTACT_EMAIL"),
        env_aliases: &[],
        requirement: Requirement::RequiredFor(Capability::PublishBeyondWorld),
        setup: SetupVisibility::AskedWhenPublishing,
        secret: false,
        default: None,
        validators: EMAIL,
        capability: Some(Capability::PublishBeyondWorld),
        what_to_set: "An address a copyright notice can be served on, reachable without an account.",
        what_is_limited: "Content cannot be published beyond a world. Playing privately is unaffected.",
        group: "Copyright notices",
        since: "0.40",
    },
    SettingDeclaration {
        key: "notice.contact_postal_address",
        kind: Kind::Text,
        backing: Backing::Row,
        env_var: Some("THUNDERFORGE_NOTICE_CONTACT_ADDRESS"),
        env_aliases: &[],
        requirement: Requirement::RequiredFor(Capability::PublishBeyondWorld),
        setup: SetupVisibility::AskedWhenPublishing,
        secret: false,
        default: None,
        validators: NAME,
        capability: Some(Capability::PublishBeyondWorld),
        what_to_set: "A postal address for the notice contact, which the designation is required to carry.",
        what_is_limited: "Content cannot be published beyond a world. Playing privately is unaffected.",
        group: "Copyright notices",
        since: "0.40",
    },
    // -- Operator prose for the legal pages ---------------------------------
    //
    // The three settings with no environment form. A multi-paragraph clause is
    // not something an environment variable holds, and pretending otherwise
    // would produce a variable nobody could use.
    SettingDeclaration {
        key: "legal.terms_change_notice",
        kind: Kind::Prose,
        backing: Backing::Row,
        env_var: None,
        env_aliases: &[],
        requirement: Requirement::Optional,
        setup: SetupVisibility::AskedWhenPublishing,
        secret: false,
        default: None,
        validators: NONE,
        capability: Some(Capability::PublishTerms),
        what_to_set: "How this instance tells people the terms have changed.",
        what_is_limited: "The terms of service keep the shipped placeholder for that clause.",
        group: "Legal prose",
        since: "0.40",
    },
    SettingDeclaration {
        key: "legal.community_addendum",
        kind: Kind::Prose,
        backing: Backing::Row,
        env_var: None,
        env_aliases: &[],
        requirement: Requirement::Optional,
        setup: SetupVisibility::AskedWhenPublishing,
        secret: false,
        default: None,
        validators: NONE,
        capability: Some(Capability::PublishTerms),
        what_to_set: "Any additional rules this community adds to the shipped terms.",
        what_is_limited: "The terms of service carry no community-specific rules.",
        group: "Legal prose",
        since: "0.40",
    },
    SettingDeclaration {
        key: "legal.minimum_age_statement",
        kind: Kind::Prose,
        backing: Backing::Row,
        env_var: None,
        env_aliases: &[],
        requirement: Requirement::Optional,
        setup: SetupVisibility::AskedWhenPublishing,
        secret: false,
        default: None,
        validators: NONE,
        capability: Some(Capability::PublishTerms),
        what_to_set: "The minimum age this instance admits, in the operator's own words.",
        what_is_limited: "The terms of service keep the shipped placeholder for the age statement.",
        group: "Legal prose",
        since: "0.40",
    },
    // -- Mail ---------------------------------------------------------------
    //
    // Declared here, delivered elsewhere: the transport, the outbox and the
    // sender are spec 040's US4. A declaration with nothing behind it yet is
    // still worth having, because it is what lets readiness say "this instance
    // cannot send mail, and here is what to set" rather than saying nothing.
    SettingDeclaration {
        key: "mail.enabled",
        kind: Kind::Bool,
        backing: Backing::Row,
        env_var: Some("THUNDERFORGE_SMTP_ENABLED"),
        env_aliases: &[],
        requirement: Requirement::Optional,
        setup: SetupVisibility::Asked,
        secret: false,
        default: Some("false"),
        validators: &[Validator::BoolLike],
        capability: Some(Capability::SendMail),
        what_to_set: "Turn mail on once the server details below are right.",
        what_is_limited: "Nothing is sent; messages wait rather than being discarded.",
        group: "Mail",
        since: "0.40",
    },
    SettingDeclaration {
        key: "mail.host",
        kind: Kind::Text,
        backing: Backing::Row,
        env_var: Some("THUNDERFORGE_SMTP_HOST"),
        env_aliases: &[],
        requirement: Requirement::RequiredFor(Capability::SendMail),
        setup: SetupVisibility::Asked,
        secret: false,
        default: None,
        validators: TEXT,
        capability: Some(Capability::SendMail),
        what_to_set: "The hostname of the SMTP server this instance sends through.",
        what_is_limited: "The instance cannot send mail. Everything else works.",
        group: "Mail",
        since: "0.40",
    },
    SettingDeclaration {
        key: "mail.port",
        kind: Kind::Port,
        backing: Backing::Row,
        env_var: Some("THUNDERFORGE_SMTP_PORT"),
        env_aliases: &[],
        requirement: Requirement::RequiredFor(Capability::SendMail),
        setup: SetupVisibility::Asked,
        secret: false,
        default: Some("587"),
        validators: &[Validator::PortRange],
        capability: Some(Capability::SendMail),
        what_to_set: "The port the SMTP server listens on — 587 for STARTTLS, 465 for implicit TLS.",
        what_is_limited: "The instance cannot send mail. Everything else works.",
        group: "Mail",
        since: "0.40",
    },
    SettingDeclaration {
        key: "mail.security",
        kind: Kind::Enum(MAIL_SECURITY),
        backing: Backing::Row,
        env_var: Some("THUNDERFORGE_SMTP_SECURITY"),
        env_aliases: &[],
        requirement: Requirement::RequiredFor(Capability::SendMail),
        setup: SetupVisibility::Asked,
        secret: false,
        default: Some("starttls"),
        validators: &[Validator::OneOf(MAIL_SECURITY)],
        capability: Some(Capability::SendMail),
        what_to_set: "How the connection is secured: none, starttls or implicit.",
        what_is_limited: "The instance cannot send mail. Everything else works.",
        group: "Mail",
        since: "0.40",
    },
    SettingDeclaration {
        key: "mail.username",
        kind: Kind::Text,
        backing: Backing::Row,
        env_var: Some("THUNDERFORGE_SMTP_USERNAME"),
        env_aliases: &[],
        requirement: Requirement::Optional,
        setup: SetupVisibility::Asked,
        secret: false,
        default: None,
        validators: TEXT,
        capability: Some(Capability::SendMail),
        what_to_set: "The account the SMTP server authenticates, when it asks for one.",
        what_is_limited: "Nothing, unless the server requires authentication.",
        group: "Mail",
        since: "0.40",
    },
    SettingDeclaration {
        key: "mail.password",
        kind: Kind::Text,
        backing: Backing::Row,
        env_var: Some("THUNDERFORGE_SMTP_PASSWORD"),
        env_aliases: &[],
        requirement: Requirement::Optional,
        setup: SetupVisibility::Asked,
        secret: true,
        default: None,
        validators: &[Validator::NonEmptyAfterTrim],
        capability: Some(Capability::SendMail),
        what_to_set: "The password for that account. It is stored encrypted and never displayed again.",
        what_is_limited: "Nothing, unless the server requires authentication.",
        group: "Mail",
        since: "0.40",
    },
    SettingDeclaration {
        key: "mail.from_address",
        kind: Kind::Email,
        backing: Backing::Row,
        env_var: Some("THUNDERFORGE_SMTP_FROM_ADDRESS"),
        env_aliases: &[],
        requirement: Requirement::RequiredFor(Capability::SendMail),
        setup: SetupVisibility::Asked,
        secret: false,
        default: None,
        validators: EMAIL,
        capability: Some(Capability::SendMail),
        what_to_set: "The address mail from this instance is sent from.",
        what_is_limited: "The instance cannot send mail. Everything else works.",
        group: "Mail",
        since: "0.40",
    },
    SettingDeclaration {
        key: "mail.from_name",
        kind: Kind::Text,
        backing: Backing::Row,
        env_var: Some("THUNDERFORGE_SMTP_FROM_NAME"),
        env_aliases: &[],
        requirement: Requirement::Optional,
        setup: SetupVisibility::Asked,
        secret: false,
        default: None,
        validators: TEXT,
        capability: Some(Capability::SendMail),
        what_to_set: "The name that appears beside the sending address.",
        what_is_limited: "Mail is sent from a bare address with no display name.",
        group: "Mail",
        since: "0.40",
    },
    // -- GitHub applications ------------------------------------------------
    //
    // Declared here so they resolve by the one rule and appear in one list.
    // **These nine are the only place a variable name for these credentials is
    // written down**, and they serve both scales: three scopes (global, and one
    // per subsystem) by three fields.
    //
    // Which application a subsystem actually uses is `crate::github_apps`
    // (spec 040 US5, ADR-090) — not here, and not by this file's ordering. Two
    // rules live there and neither is expressible as a declaration: scope is
    // the outer axis and source the inner one, so a subsystem application set
    // in the screens beats a global one set in the environment; and an
    // application resolves whole, so a partially specified subsystem is
    // stepped over entire rather than completed from the global one's key.
    //
    // The private key's three forms are **one declaration with two aliases**,
    // so `Resolved::fixed_by` names the variable that actually set the value
    // and `github_apps::private_key_bytes` decides the form from that rather
    // than by sniffing the value.
    //
    // **They are ordered file, base64, inline, and the order is load-bearing.**
    // `env_name_in_use` takes `env_var` first and then the aliases in order, so
    // this list IS the precedence — and it has to be the same precedence
    // `repo_host::read_private_key` has had since spec 034: a path wins,
    // because "an operator who has gone to the trouble of a mounted secret
    // should not be silently overridden by a stale inline value left in an
    // environment file". It was written the other way round first, primary
    // last, and a deployment setting both a `_FILE` and an inline key then
    // resolved to *different keys* through `registration_from_env` and through
    // `github_apps` — two answers for one configuration, from the function
    // whose whole job is to give the same answer as the old one.
    // `github_apps_tests::the_three_key_forms_keep_their_precedence` is that
    // bug, kept.
    //
    // A tenth declaration for the file form is not possible here in any case:
    // `everything_but_prose_can_be_set_by_the_environment` requires it to have
    // a variable and `no_two_declarations_read_the_same_variable` forbids it
    // from reusing this one's. That is why the file form stays an environment
    // form and a mounted secret is never copied into the database.
    SettingDeclaration {
        key: "github_app.global.client_id",
        kind: Kind::Text,
        backing: Backing::Row,
        env_var: Some("GLOBAL_GITHUB_APP_CLIENT_ID"),
        env_aliases: &[],
        requirement: Requirement::Optional,
        setup: SetupVisibility::Offered,
        secret: false,
        default: None,
        validators: TEXT,
        capability: None,
        what_to_set: "The client ID of a GitHub application every subsystem may fall back to.",
        what_is_limited: "Each subsystem needs its own application.",
        group: "GitHub applications",
        since: "0.40",
    },
    SettingDeclaration {
        key: "github_app.global.slug",
        kind: Kind::Text,
        backing: Backing::Row,
        env_var: Some("GLOBAL_GITHUB_APP_SLUG"),
        env_aliases: &[],
        requirement: Requirement::Optional,
        setup: SetupVisibility::Offered,
        secret: false,
        default: None,
        validators: TEXT,
        capability: None,
        what_to_set: "That application's URL slug, which the install link is built from.",
        what_is_limited: "Each subsystem needs its own application.",
        group: "GitHub applications",
        since: "0.40",
    },
    SettingDeclaration {
        key: "github_app.global.private_key",
        kind: Kind::Text,
        backing: Backing::Row,
        // Ordered file, base64, inline — see the note at the head of this
        // group. The order is the precedence, and it must match
        // `repo_host::read_private_key`'s.
        env_var: Some("GLOBAL_GITHUB_APP_PRIVATE_KEY_FILE"),
        env_aliases: &[
            "GLOBAL_GITHUB_APP_PRIVATE_KEY_BASE64",
            "GLOBAL_GITHUB_APP_PRIVATE_KEY",
        ],
        requirement: Requirement::Optional,
        setup: SetupVisibility::Offered,
        secret: true,
        default: None,
        validators: &[Validator::NonEmptyAfterTrim],
        capability: None,
        what_to_set: "That application's PEM private key. The environment names it three ways, highest precedence first: `..._PRIVATE_KEY_FILE` (a path to the PEM), `..._PRIVATE_KEY_BASE64` (the .env-safe form) and `..._PRIVATE_KEY` (the PEM itself).",
        what_is_limited: "Each subsystem needs its own application.",
        group: "GitHub applications",
        since: "0.40",
    },
    SettingDeclaration {
        key: "github_app.sync.client_id",
        kind: Kind::Text,
        backing: Backing::Row,
        env_var: Some(crate::repo_host::APP_ID_ENV),
        env_aliases: &[],
        requirement: Requirement::RequiredFor(Capability::SyncLore),
        setup: SetupVisibility::Offered,
        secret: false,
        default: None,
        validators: TEXT,
        capability: Some(Capability::SyncLore),
        what_to_set: "The client ID of the GitHub application lore synchronisation acts as.",
        what_is_limited: "A world cannot be connected to a repository.",
        group: "GitHub applications",
        since: "0.40",
    },
    SettingDeclaration {
        key: "github_app.sync.slug",
        kind: Kind::Text,
        backing: Backing::Row,
        env_var: Some(crate::repo_host::APP_SLUG_ENV),
        env_aliases: &[],
        requirement: Requirement::RequiredFor(Capability::SyncLore),
        setup: SetupVisibility::Offered,
        secret: false,
        default: None,
        validators: TEXT,
        capability: Some(Capability::SyncLore),
        what_to_set: "That application's URL slug. Not interchangeable with the client ID.",
        what_is_limited: "A world cannot be connected to a repository.",
        group: "GitHub applications",
        since: "0.40",
    },
    SettingDeclaration {
        key: "github_app.sync.private_key",
        kind: Kind::Text,
        backing: Backing::Row,
        env_var: Some(crate::repo_host::APP_PRIVATE_KEY_FILE_ENV),
        env_aliases: &[
            crate::repo_host::APP_PRIVATE_KEY_BASE64_ENV,
            crate::repo_host::APP_PRIVATE_KEY_ENV,
        ],
        requirement: Requirement::RequiredFor(Capability::SyncLore),
        setup: SetupVisibility::Offered,
        secret: true,
        default: None,
        validators: &[Validator::NonEmptyAfterTrim],
        capability: Some(Capability::SyncLore),
        what_to_set: "That application's PEM private key. The environment names it three ways, highest precedence first: `..._PRIVATE_KEY_FILE` (a path to the PEM), `..._PRIVATE_KEY_BASE64` (the .env-safe form) and `..._PRIVATE_KEY` (the PEM itself).",
        what_is_limited: "A world cannot be connected to a repository.",
        group: "GitHub applications",
        since: "0.40",
    },
    SettingDeclaration {
        key: "github_app.feedback.client_id",
        kind: Kind::Text,
        backing: Backing::Row,
        env_var: Some("FEEDBACK_GITHUB_APP_CLIENT_ID"),
        env_aliases: &[],
        requirement: Requirement::Optional,
        setup: SetupVisibility::Offered,
        secret: false,
        default: None,
        validators: TEXT,
        capability: Some(Capability::Feedback),
        what_to_set: "The client ID of the GitHub application feedback is raised as.",
        what_is_limited: "Feedback cannot be raised on the project's repository.",
        group: "GitHub applications",
        since: "0.40",
    },
    SettingDeclaration {
        key: "github_app.feedback.slug",
        kind: Kind::Text,
        backing: Backing::Row,
        env_var: Some("FEEDBACK_GITHUB_APP_SLUG"),
        env_aliases: &[],
        requirement: Requirement::Optional,
        setup: SetupVisibility::Offered,
        secret: false,
        default: None,
        validators: TEXT,
        capability: Some(Capability::Feedback),
        what_to_set: "That application's URL slug.",
        what_is_limited: "Feedback cannot be raised on the project's repository.",
        group: "GitHub applications",
        since: "0.40",
    },
    SettingDeclaration {
        key: "github_app.feedback.private_key",
        kind: Kind::Text,
        backing: Backing::Row,
        env_var: Some("FEEDBACK_GITHUB_APP_PRIVATE_KEY_FILE"),
        env_aliases: &[
            "FEEDBACK_GITHUB_APP_PRIVATE_KEY_BASE64",
            "FEEDBACK_GITHUB_APP_PRIVATE_KEY",
        ],
        requirement: Requirement::Optional,
        setup: SetupVisibility::Offered,
        secret: true,
        default: None,
        validators: &[Validator::NonEmptyAfterTrim],
        capability: Some(Capability::Feedback),
        what_to_set: "That application's PEM private key. The environment names it three ways, highest precedence first: `..._PRIVATE_KEY_FILE` (a path to the PEM), `..._PRIVATE_KEY_BASE64` (the .env-safe form) and `..._PRIVATE_KEY` (the PEM itself).",
        what_is_limited: "Feedback cannot be raised on the project's repository.",
        group: "GitHub applications",
        since: "0.40",
    },
    // -- The realm manifest, presented rather than moved ---------------------
    //
    // Still `manifest.json`, still seeded from `config/realm-defaults.json`,
    // still written through `admin::update_manifest_key`. What changes is that
    // they resolve by the same rule and report a source (research.md § R6).
    SettingDeclaration {
        key: "realm_name",
        kind: Kind::Text,
        backing: Backing::ManifestFile("realm_name"),
        env_var: Some("THUNDERFORGE_REALM_NAME"),
        env_aliases: &[],
        requirement: Requirement::Optional,
        setup: SetupVisibility::Offered,
        secret: false,
        default: None,
        validators: TEXT,
        capability: None,
        what_to_set: "What this instance calls itself.",
        what_is_limited: "The instance is named as it shipped.",
        group: "Realm",
        since: "0.40",
    },
    SettingDeclaration {
        key: "support_email",
        kind: Kind::Email,
        backing: Backing::ManifestFile("support_email"),
        env_var: Some("THUNDERFORGE_SUPPORT_EMAIL"),
        env_aliases: &[],
        requirement: Requirement::RequiredAtSetup,
        setup: SetupVisibility::Asked,
        secret: false,
        default: None,
        validators: EMAIL,
        capability: Some(Capability::IdentifyOperator),
        what_to_set: "An address people can reach for help with this instance.",
        what_is_limited: "Nobody using this instance has anywhere to write for help.",
        group: "Support",
        since: "0.40",
    },
    SettingDeclaration {
        key: "welcome_message",
        kind: Kind::Text,
        backing: Backing::ManifestFile("welcome_message"),
        env_var: Some("THUNDERFORGE_WELCOME_MESSAGE"),
        env_aliases: &[],
        requirement: Requirement::Optional,
        setup: SetupVisibility::Offered,
        secret: false,
        default: None,
        validators: TEXT,
        capability: None,
        what_to_set: "What a new arrival is greeted with.",
        what_is_limited: "New arrivals see the greeting the instance shipped with.",
        group: "Realm",
        since: "0.40",
    },
    SettingDeclaration {
        key: "interface_pack_id",
        kind: Kind::Text,
        backing: Backing::ManifestFile("interface_pack_id"),
        env_var: Some("THUNDERFORGE_INTERFACE_PACK_ID"),
        env_aliases: &[],
        requirement: Requirement::Optional,
        setup: SetupVisibility::Offered,
        secret: false,
        default: None,
        validators: TEXT,
        capability: None,
        what_to_set: "Which interface pack a new world starts with.",
        what_is_limited: "New worlds use the shipped interface pack.",
        group: "Realm",
        since: "0.40",
    },
    SettingDeclaration {
        key: "asset_pack_id",
        kind: Kind::Text,
        backing: Backing::ManifestFile("asset_pack_id"),
        env_var: Some("THUNDERFORGE_ASSET_PACK_ID"),
        env_aliases: &[],
        requirement: Requirement::Optional,
        setup: SetupVisibility::Offered,
        secret: false,
        default: None,
        validators: TEXT,
        capability: None,
        what_to_set: "Which asset pack a new world starts with.",
        what_is_limited: "New worlds use the shipped asset pack.",
        group: "Realm",
        since: "0.40",
    },
    SettingDeclaration {
        key: "default_game_system_id",
        kind: Kind::Text,
        backing: Backing::ManifestFile("default_game_system_id"),
        env_var: Some("THUNDERFORGE_DEFAULT_GAME_SYSTEM_ID"),
        env_aliases: &[],
        requirement: Requirement::Optional,
        setup: SetupVisibility::Offered,
        secret: false,
        default: None,
        validators: TEXT,
        capability: None,
        what_to_set: "Which game system a world starts with when nobody names one.",
        what_is_limited: "A world created without naming a system has no system at all.",
        group: "Realm",
        since: "0.40",
    },
    // -- Where uploaded files live ------------------------------------------
    //
    // Offered rather than asked: a deployment that brought its own storage in
    // the environment has already answered, and one that has not can still
    // play \u{2014} it just cannot hold a picture. Readiness says so, and the last
    // step of setup is where an operator who forgot gets to say it.
    SettingDeclaration {
        key: "storage.endpoint",
        kind: Kind::Url,
        backing: Backing::Row,
        env_var: Some("RUSTFS_ENDPOINT"),
        env_aliases: &[],
        requirement: Requirement::RequiredFor(Capability::StoreAssets),
        setup: SetupVisibility::Offered,
        secret: false,
        default: Some("http://localhost:9000"),
        validators: &[Validator::NonEmptyAfterTrim],
        capability: Some(Capability::StoreAssets),
        what_to_set: "The URL of the S3-compatible object store this instance writes to.",
        what_is_limited: "Maps, tokens, portraits and attachments cannot be stored or served. Play without images is unaffected.",
        group: "Storage",
        since: "0.64",
    },
    SettingDeclaration {
        key: "storage.region",
        kind: Kind::Text,
        backing: Backing::Row,
        env_var: Some("RUSTFS_REGION"),
        env_aliases: &[],
        requirement: Requirement::RequiredFor(Capability::StoreAssets),
        setup: SetupVisibility::Offered,
        secret: false,
        default: Some("us-east-1"),
        validators: TEXT,
        capability: Some(Capability::StoreAssets),
        what_to_set: "The region the object store expects. `us-east-1` is the usual answer for a self-hosted store that does not care.",
        what_is_limited: "Maps, tokens, portraits and attachments cannot be stored or served. Play without images is unaffected.",
        group: "Storage",
        since: "0.64",
    },
    SettingDeclaration {
        key: "storage.bucket",
        kind: Kind::Text,
        backing: Backing::Row,
        env_var: Some("RUSTFS_BUCKET"),
        env_aliases: &[],
        requirement: Requirement::RequiredFor(Capability::StoreAssets),
        setup: SetupVisibility::Offered,
        secret: false,
        default: Some("thunderforge-canvas-assets"),
        validators: TEXT,
        capability: Some(Capability::StoreAssets),
        what_to_set: "The bucket uploaded files are written into. It must already exist, or the instance must be able to create it. Changing it on an instance that already holds uploads leaves those uploads behind in the old bucket.",
        what_is_limited: "Maps, tokens, portraits and attachments cannot be stored or served. Play without images is unaffected.",
        group: "Storage",
        since: "0.64",
    },
    SettingDeclaration {
        key: "storage.access_key",
        kind: Kind::Text,
        backing: Backing::Row,
        env_var: Some("RUSTFS_ROOT_ACCESS_KEY"),
        env_aliases: &[],
        requirement: Requirement::RequiredFor(Capability::StoreAssets),
        setup: SetupVisibility::Offered,
        secret: false,
        default: Some("thunderforge-rustfs-root"),
        validators: TEXT,
        capability: Some(Capability::StoreAssets),
        what_to_set: "The access key the instance signs object-store requests with.",
        what_is_limited: "Maps, tokens, portraits and attachments cannot be stored or served. Play without images is unaffected.",
        group: "Storage",
        since: "0.64",
    },
    SettingDeclaration {
        key: "storage.secret_key",
        kind: Kind::Text,
        backing: Backing::Row,
        env_var: Some("RUSTFS_ROOT_SECRET_KEY"),
        env_aliases: &[],
        requirement: Requirement::RequiredFor(Capability::StoreAssets),
        setup: SetupVisibility::Offered,
        secret: true,
        // No default, because `no_secret_has_a_default` is right: a shipped
        // default for a secret is a shipped credential, and this one would be
        // the bundled RustFS root password. The bundled stack still works
        // without an answer here — `RustFsConfig::from_settings` carries the
        // dev fallback, where it is a development convenience rather than a
        // declared setting an operator could mistake for configuration — but
        // readiness reports the capability as unavailable until somebody says
        // what the secret is, which is the honest report.
        default: None,
        validators: TEXT,
        capability: Some(Capability::StoreAssets),
        what_to_set: "The secret key paired with the access key. Stored encrypted and never shown again.",
        what_is_limited: "Maps, tokens, portraits and attachments cannot be stored or served. Play without images is unaffected.",
        group: "Storage",
        since: "0.64",
    },
    // --- Features (spec 068) ---------------------------------------------
    //
    // A flag is a boolean setting in this group, listed in
    // `settings::features::FEATURES`. See that file for the rule and for how
    // to add one; `docs/CONTRIBUTING.md` says when a feature should take one.
    SettingDeclaration {
        key: "feature.book_import",
        kind: Kind::Bool,
        backing: Backing::Row,
        env_var: Some("THUNDERFORGE_FEATURE_BOOK_IMPORT"),
        env_aliases: &[],
        requirement: Requirement::Optional,
        setup: SetupVisibility::Offered,
        secret: false,
        default: Some("true"),
        validators: &[Validator::BoolLike],
        capability: None,
        what_to_set: "Whether members may read a source book into their library.",
        what_is_limited: "Nobody can import a book. Books already imported stay on their shelves and in their worlds.",
        group: "Features",
        since: "0.68",
    },
    SettingDeclaration {
        key: "feature.demo",
        kind: Kind::Bool,
        backing: Backing::Row,
        env_var: Some("THUNDERFORGE_FEATURE_DEMO"),
        env_aliases: &[],
        requirement: Requirement::Optional,
        setup: SetupVisibility::Offered,
        secret: false,
        default: Some("false"),
        validators: &[Validator::BoolLike],
        capability: None,
        what_to_set: "Whether anyone, signed in or not, may open the demo world at /demo. It runs in their browser and writes nothing to this instance.",
        what_is_limited: "There is no demo: /demo is not found and nothing links to it.",
        group: "Features",
        since: "0.74",
    },
    SettingDeclaration {
        key: "feature.download_in_parts",
        kind: Kind::Bool,
        backing: Backing::Row,
        env_var: Some("THUNDERFORGE_FEATURE_DOWNLOAD_IN_PARTS"),
        env_aliases: &[],
        requirement: Requirement::Optional,
        setup: SetupVisibility::Offered,
        secret: false,
        default: Some("true"),
        validators: &[Validator::BoolLike],
        capability: None,
        what_to_set: "Whether browsers fetch a large scene, asset or engine file in several parts that resume after a dropped connection.",
        what_is_limited: "Every file is one plain request again: a dropped connection starts a large download over from the beginning.",
        group: "Features",
        since: "0.80",
    },
    SettingDeclaration {
        key: "feature.sheet_import",
        kind: Kind::Bool,
        backing: Backing::Row,
        env_var: Some("THUNDERFORGE_FEATURE_SHEET_IMPORT"),
        env_aliases: &[],
        requirement: Requirement::Optional,
        setup: SetupVisibility::Offered,
        secret: false,
        default: Some("false"),
        validators: &[Validator::BoolLike],
        capability: None,
        what_to_set: "Whether a player may bring a character in from an exported character sheet PDF, onto a character they hold in a world.",
        what_is_limited: "Players cannot bring a character in from a PDF.",
        group: "Features",
        since: "0.81",
    },
];
