import path from "node:path";
import { expect, test, type Browser, type Page } from "./test";
import {
  openAdminPage,
  readSetting,
  writeSetting,
  writeSettingOrThrow,
} from "./admin";
import { inviteAndJoinAsPlayer, uniqueSuffix } from "./helpers";
import { must } from "../../playtest/table";

/**
 * Spec 048: what the sheet-import specs share. Every sheet is generated by
 * a pack's tests from an invented character; no real export is used.
 */

export const SHEET_IMPORT_FLAG = "feature.sheet_import";

/** A fixture a pack's sheet tests generate, by file name: the 5e pack's
 * unless another system is named. */
export function sheetFixture(file: string, system = "dnd5e"): string {
  return path.resolve(
    __dirname,
    `../../../../packs/systems/${system}/sheet/tests/fixtures`,
    file,
  );
}

/**
 * Switch the flag on for this file's run and put back what was found, as
 * `instance-feature-flags.spec.ts` does. Call at the top of a spec file.
 */
export function withSheetImportOn(): void {
  let admin: Page | null = null;
  let original: string | null = null;

  test.beforeAll(async ({ browser }) => {
    admin = await openAdminPage(browser);
    const found = await readSetting(admin, SHEET_IMPORT_FLAG);
    test.skip(
      found.source === "ENVIRONMENT" && found.value !== "true",
      `${SHEET_IMPORT_FLAG} is fixed off by ${found.fixedBy}`,
    );
    original = found.source === "INSTANCE" ? found.value : null;
    if (found.source !== "ENVIRONMENT") {
      await writeSettingOrThrow(admin, SHEET_IMPORT_FLAG, "true");
    }
  });

  test.afterAll(async () => {
    if (!admin) return;
    await writeSetting(admin, SHEET_IMPORT_FLAG, original);
    await admin.context().close();
  });
}

export interface ImportRecordSeen {
  id: string;
  correctedFields: string[];
}

/** The actor's imports, as `page` may see them. */
export async function importsOf(
  page: Page,
  actorId: string,
): Promise<ImportRecordSeen[]> {
  const { actorImports } = await must<{ actorImports: ImportRecordSeen[] }>(
    page,
    `query ($actorId: UUID!) {
      actorImports(actorId: $actorId) { id correctedFields }
    }`,
    { actorId },
  );
  return actorImports;
}

/** Open the import page and wait for it. */
export async function openImport(
  page: Page,
  worldId: string,
  actorId: string,
): Promise<void> {
  await page.goto(`/world/${worldId}/actor/${actorId}/import`);
  await expect(page.getByTestId("sheet-import-page")).toBeVisible({
    timeout: 15_000,
  });
}

/** Pick a sheet and wait for the review. */
export async function review(
  page: Page,
  file: string,
  system = "dnd5e",
): Promise<void> {
  await expect(page.getByTestId("sheet-import-page")).toBeVisible({
    timeout: 15_000,
  });
  await page
    .getByTestId("sheet-import-file")
    .setInputFiles(sheetFixture(file, system));
  await expect(page.getByTestId("sheet-import-fields")).toBeVisible({
    timeout: 30_000,
  });
}

/** The GM makes a named character; a new player joins and claims it. */
export async function claimNamedCharacter(
  browser: Browser,
  gm: Page,
  worldId: string,
): Promise<{ player: Page; actorId: string }> {
  const name = `Isolde ${uniqueSuffix()}`;
  await gm.goto(`/world/${worldId}/players`);
  await gm.getByTestId("new-character-name").fill(name);
  await gm.getByTestId("new-character-submit").click();
  await expect(gm.getByTestId("new-character-made")).toHaveText(
    `${name} is ready to be claimed.`,
    { timeout: 10_000 },
  );
  const player = await inviteAndJoinAsPlayer(browser, gm, worldId, "e2esheet");
  await player.goto(`/world/${worldId}/actor-select`);
  const row = player
    .getByTestId("available-actor-row")
    .filter({ hasText: name });
  await expect(row).toHaveCount(1, { timeout: 15_000 });
  await row.getByRole("button", { name: "Select" }).click();
  await player.waitForURL(new RegExp(`/world/${worldId}$`), {
    timeout: 15_000,
  });
  const { myActorClaim } = await must<{
    myActorClaim: { actorId: string } | null;
  }>(
    player,
    `query ($worldId: UUID!) { myActorClaim(worldId: $worldId) { actorId } }`,
    { worldId },
  );
  return { player, actorId: myActorClaim!.actorId };
}

/** An NPC the GM makes directly. */
export async function createNpc(
  gm: Page,
  worldId: string,
  gameSystemId: string,
): Promise<string> {
  const { createActor } = await must<{ createActor: { id: string } }>(
    gm,
    `mutation ($input: CreateActorInput!) { createActor(input: $input) { id } }`,
    {
      input: {
        worldId,
        label: `Double ${uniqueSuffix()}`,
        isNpc: true,
        gameSystemId,
      },
    },
  );
  return createActor.id;
}

/**
 * Bring `file` in onto `actorId` through the page, as a player would: open
 * the import page, pick the sheet, wait for the review, accept, and wait to
 * land back on the character.
 */
export async function bringIn(
  page: Page,
  worldId: string,
  actorId: string,
  file: string,
): Promise<void> {
  await openImport(page, worldId, actorId);
  await review(page, file);
  await page.getByTestId("sheet-import-accept").click();
  await expect(page).toHaveURL(
    new RegExp(`/world/${worldId}/actor/${actorId}/view$`),
    { timeout: 30_000 },
  );
}

export interface StagedSeen {
  id: string;
  kind: string;
  name: string;
  state: "PENDING" | "ACCEPTED" | "DECLINED";
  broughtBy: { id: string; displayName: string };
  abilityId: string | null;
  itemId: string | null;
}

/** What players brought into the world, as `page` may see it. */
export async function stagedIn(
  page: Page,
  worldId: string,
): Promise<StagedSeen[]> {
  const { stagedContent } = await must<{ stagedContent: StagedSeen[] }>(
    page,
    `query ($worldId: UUID!) {
      stagedContent(worldId: $worldId) {
        id kind name state broughtBy { id displayName }
        abilityId itemId
      }
    }`,
    { worldId },
  );
  return stagedContent;
}

/**
 * The one piece of that kind and name, or a failure that says so. Two
 * players whose sheets describe a piece differently stage it twice, so
 * `broughtBy` narrows to one player's.
 */
export async function stagedPiece(
  page: Page,
  worldId: string,
  kind: string,
  name: string,
  broughtBy?: string,
): Promise<StagedSeen> {
  const found = (await stagedIn(page, worldId)).filter(
    (piece) =>
      piece.kind === kind &&
      piece.name === name &&
      (broughtBy === undefined || piece.broughtBy.id === broughtBy),
  );
  expect(found, `one staged ${kind} named ${name}`).toHaveLength(1);
  return found[0];
}

/** The queue on the compendium's "Brought by players" tab. */
export async function openBroughtByPlayers(
  page: Page,
  worldId: string,
): Promise<void> {
  await page.goto(`/world/${worldId}/compendium?tab=brought`);
  await expect(
    page.getByRole("region", { name: "Brought by players" }),
  ).toBeVisible({ timeout: 20_000 });
}
