/**
 * The demo party: twelve heroes, one per classic role, for demo worlds and
 * as a builder's starting points. Drawn by us from `parts.ts`, so they are
 * ours to redistribute.
 */
import { SKIN_TONES, type HeroSpec } from "./spec.ts";

export interface HeroPreset {
  /** Stable id: file names and seed rows are keyed by it. */
  slug: string;
  spec: HeroSpec;
}

export const PRESET_HEROES: readonly HeroPreset[] = [
  {
    slug: "sir-pip",
    spec: {
      name: "Sir Pip",
      title: "the Stalwart Knight",
      skin: SKIN_TONES.peach,
      hair: "short",
      hairColor: "#c98a3c",
      headgear: "helm",
      headgearColor: "#b8c2cc",
      accent: "#d94a4a",
      outfit: "#3d6fd1",
      emblem: "cross",
      prop: "sword",
      glow: "#9fc3ff",
    },
  },
  {
    slug: "mira-starweave",
    spec: {
      name: "Mira Starweave",
      title: "the Wizard",
      skin: SKIN_TONES.umber,
      hair: "long",
      hairColor: "#2b2233",
      headgear: "wizard",
      headgearColor: "#6a4bc4",
      outfit: "#6a4bc4",
      prop: "staff",
      eyes: "#5a3bb0",
      glow: "#c9b8ff",
    },
  },
  {
    slug: "nettle",
    spec: {
      name: "Nettle",
      title: "the Rogue",
      skin: SKIN_TONES.porcelain,
      hair: "short",
      hairColor: "#3b2a1f",
      headgear: "hood",
      headgearColor: "#2f5d46",
      outfit: "#2f5d46",
      mouth: "smirk",
      prop: "dagger",
      glow: "#9ad6b4",
    },
  },
  {
    slug: "brother-oak",
    spec: {
      name: "Brother Oak",
      title: "the Cleric",
      skin: SKIN_TONES.ebony,
      hair: "bald",
      beard: true,
      beardColor: "#d9d2c5",
      outfit: "#f2efe6",
      trim: "#d9a441",
      emblem: "sun",
      prop: "hammer",
      glow: "#ffe8a3",
      ring: "#d9a441",
    },
  },
  {
    slug: "fenna-swiftbow",
    spec: {
      name: "Fenna Swiftbow",
      title: "the Elf Ranger",
      skin: SKIN_TONES.honey,
      ears: "pointed",
      hair: "braids",
      hairColor: "#e8d27a",
      outfit: "#4e8a3a",
      prop: "bow",
      eyes: "#2f7a3a",
      glow: "#b8e6a0",
    },
  },
  {
    slug: "lark",
    spec: {
      name: "Lark",
      title: "the Bard",
      skin: SKIN_TONES.bronze,
      hair: "curly",
      hairColor: "#3b2a1f",
      headgear: "cap",
      headgearColor: "#c43b52",
      accent: "#f4c542",
      outfit: "#c43b52",
      mouth: "grin",
      prop: "lute",
      glow: "#ffb3c1",
    },
  },
  {
    slug: "grom",
    spec: {
      name: "Grom",
      title: "the Orc Barbarian",
      skin: SKIN_TONES.sage,
      tusks: true,
      hair: "bald",
      headgear: "horned",
      headgearColor: "#8a6a4a",
      outfit: "#8a4a2f",
      prop: "axe",
      eyes: "#7a3b1f",
      glow: "#e6b88f",
    },
  },
  {
    slug: "willow",
    spec: {
      name: "Willow",
      title: "the Druid",
      skin: SKIN_TONES.bronze,
      hair: "long",
      hairColor: "#7a4a2a",
      headgear: "leaves",
      outfit: "#6a8f3a",
      prop: "vine",
      eyes: "#3a6a2a",
      glow: "#cfe8a0",
    },
  },
  {
    slug: "dame-aurora",
    spec: {
      name: "Dame Aurora",
      title: "the Paladin",
      skin: SKIN_TONES.porcelain,
      hair: "long",
      hairColor: "#e8b04a",
      headgear: "circlet",
      accent: "#4ec3e0",
      outfit: "#d9a441",
      trim: "#f2efe6",
      emblem: "sun",
      prop: "hammer",
      eyes: "#3a6aa0",
      glow: "#fff0b3",
    },
  },
  {
    slug: "kai",
    spec: {
      name: "Kai",
      title: "the Monk",
      skin: SKIN_TONES.honey,
      hair: "bun",
      hairColor: "#2b2233",
      headgear: "headband",
      headgearColor: "#e0602f",
      outfit: "#e0892f",
      prop: "fists",
      glow: "#ffd0a3",
      ring: "#e0602f",
    },
  },
  {
    slug: "ember",
    spec: {
      name: "Ember",
      title: "the Tiefling Sorcerer",
      skin: SKIN_TONES.ember,
      hair: "spiky",
      hairColor: "#2b2233",
      headgear: "tiefling",
      outfit: "#3b2a4a",
      prop: "flame",
      eyes: "#f4c542",
      glow: "#ffb38a",
      ring: "#b8322f",
    },
  },
  {
    slug: "tink-cogsworth",
    spec: {
      name: "Tink Cogsworth",
      title: "the Gnome Artificer",
      skin: SKIN_TONES.peach,
      hair: "curly",
      hairColor: "#e0602f",
      headgear: "goggles",
      outfit: "#5a6a7a",
      emblem: "gear",
      mouth: "grin",
      prop: "wrench",
      glow: "#b8e0f0",
    },
  },
];
